project:
  type: book
  output-dir: docs


book:
  title: "STAT 255 Notes"
  author: "Andrew J. Sage"
  date: "August 8, 2025"
  chapters:
    - index.qmd
    - Ch1.qmd
    - Ch2.qmd
    - Ch3.qmd
    - Ch4.qmd


#bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#      toc: true
#      toc-depth: 2
#      documentclass: scrreprt




editor: visual

