project:
  type: book
  output-dir: docs


book:
  title: "STAT 255 Notes"
  author: "Andrew J. Sage"
  date: "8/26/2024"
  chapters:
    - index.qmd
    - Ch1.qmd
    - Ch2.qmd
    - Ch3.qmd
    - Ch4.qmd
    - Ch5.qmd
    - Ch6.qmd
    - Ch7.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
      toc: true
      toc-depth: 2
      documentclass: scrreprt




editor: visual

