<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Building and Assessing Models – STAT 255 Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch5.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Building and Assessing Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">STAT 255 Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Statistical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation-Based Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference from Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Building and Assessing Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#regression-assumptions-checks" id="toc-regression-assumptions-checks" class="nav-link" data-scroll-target="#regression-assumptions-checks"><span class="header-section-number">5.1</span> Regression Assumptions Checks</a>
  <ul class="collapse">
  <li><a href="#residual-diagnostic-plots" id="toc-residual-diagnostic-plots" class="nav-link" data-scroll-target="#residual-diagnostic-plots"><span class="header-section-number">5.1.1</span> Residual Diagnostic Plots</a></li>
  <li><a href="#example-n-v-s-lakes" id="toc-example-n-v-s-lakes" class="nav-link" data-scroll-target="#example-n-v-s-lakes"><span class="header-section-number">5.1.2</span> Example: N v S Lakes</a></li>
  <li><a href="#example-ph-model" id="toc-example-ph-model" class="nav-link" data-scroll-target="#example-ph-model"><span class="header-section-number">5.1.3</span> Example: pH Model</a></li>
  <li><a href="#example-house-prices" id="toc-example-house-prices" class="nav-link" data-scroll-target="#example-house-prices"><span class="header-section-number">5.1.4</span> Example: House Prices</a></li>
  <li><a href="#impact-of-model-assumption-violations" id="toc-impact-of-model-assumption-violations" class="nav-link" data-scroll-target="#impact-of-model-assumption-violations"><span class="header-section-number">5.1.5</span> Impact of Model Assumption Violations</a></li>
  </ul></li>
  <li><a href="#transformations" id="toc-transformations" class="nav-link" data-scroll-target="#transformations"><span class="header-section-number">5.2</span> Transformations</a>
  <ul class="collapse">
  <li><a href="#example-modeling-car-prices" id="toc-example-modeling-car-prices" class="nav-link" data-scroll-target="#example-modeling-car-prices"><span class="header-section-number">5.2.1</span> Example: Modeling Car Prices</a></li>
  <li><a href="#log-transformation" id="toc-log-transformation" class="nav-link" data-scroll-target="#log-transformation"><span class="header-section-number">5.2.2</span> Log Transformation</a></li>
  <li><a href="#inference-for-log-model" id="toc-inference-for-log-model" class="nav-link" data-scroll-target="#inference-for-log-model"><span class="header-section-number">5.2.3</span> Inference for Log Model</a></li>
  <li><a href="#log-model-interpretations" id="toc-log-model-interpretations" class="nav-link" data-scroll-target="#log-model-interpretations"><span class="header-section-number">5.2.4</span> Log Model Interpretations</a></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons"><span class="header-section-number">5.2.5</span> Model Comparisons</a></li>
  <li><a href="#log-model-visualization" id="toc-log-model-visualization" class="nav-link" data-scroll-target="#log-model-visualization"><span class="header-section-number">5.2.6</span> Log Model Visualization</a></li>
  <li><a href="#comments-on-transformations" id="toc-comments-on-transformations" class="nav-link" data-scroll-target="#comments-on-transformations"><span class="header-section-number">5.2.7</span> Comments on Transformations</a></li>
  </ul></li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression"><span class="header-section-number">5.3</span> Polynomial Regression</a></li>
  <li><a href="#models-with-interaction" id="toc-models-with-interaction" class="nav-link" data-scroll-target="#models-with-interaction"><span class="header-section-number">5.4</span> Models with Interaction</a>
  <ul class="collapse">
  <li><a href="#definition-of-interaction" id="toc-definition-of-interaction" class="nav-link" data-scroll-target="#definition-of-interaction"><span class="header-section-number">5.4.1</span> Definition of Interaction</a></li>
  <li><a href="#interaction-term" id="toc-interaction-term" class="nav-link" data-scroll-target="#interaction-term"><span class="header-section-number">5.4.2</span> Interaction Term</a></li>
  <li><a href="#interaction-models-in-r" id="toc-interaction-models-in-r" class="nav-link" data-scroll-target="#interaction-models-in-r"><span class="header-section-number">5.4.3</span> Interaction Models in R</a></li>
  <li><a href="#variability-explained" id="toc-variability-explained" class="nav-link" data-scroll-target="#variability-explained"><span class="header-section-number">5.4.4</span> Variability Explained</a></li>
  <li><a href="#considerations-for-using-interactions" id="toc-considerations-for-using-interactions" class="nav-link" data-scroll-target="#considerations-for-using-interactions"><span class="header-section-number">5.4.5</span> Considerations for Using Interactions</a></li>
  <li><a href="#when-to-include-interaction" id="toc-when-to-include-interaction" class="nav-link" data-scroll-target="#when-to-include-interaction"><span class="header-section-number">5.4.6</span> When to Include Interaction</a></li>
  <li><a href="#interaction-vs-correlation" id="toc-interaction-vs-correlation" class="nav-link" data-scroll-target="#interaction-vs-correlation"><span class="header-section-number">5.4.7</span> Interaction vs Correlation</a></li>
  </ul></li>
  <li><a href="#building-a-model-for-interpretation" id="toc-building-a-model-for-interpretation" class="nav-link" data-scroll-target="#building-a-model-for-interpretation"><span class="header-section-number">5.5</span> Building a Model for Interpretation</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">5.5.1</span> Exploratory Data Analysis</a></li>
  <li><a href="#simpsons-paradox" id="toc-simpsons-paradox" class="nav-link" data-scroll-target="#simpsons-paradox"><span class="header-section-number">5.5.2</span> Simpson’s Paradox</a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity"><span class="header-section-number">5.5.3</span> Multicollinearity</a></li>
  <li><a href="#model-comparison-tests" id="toc-model-comparison-tests" class="nav-link" data-scroll-target="#model-comparison-tests"><span class="header-section-number">5.5.4</span> Model Comparison Tests</a></li>
  <li><a href="#checking-model-assumptions" id="toc-checking-model-assumptions" class="nav-link" data-scroll-target="#checking-model-assumptions"><span class="header-section-number">5.5.5</span> Checking Model Assumptions</a></li>
  <li><a href="#interpretations" id="toc-interpretations" class="nav-link" data-scroll-target="#interpretations"><span class="header-section-number">5.5.6</span> Interpretations</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions"><span class="header-section-number">5.5.7</span> Predictions</a></li>
  <li><a href="#model-building-summary" id="toc-model-building-summary" class="nav-link" data-scroll-target="#model-building-summary"><span class="header-section-number">5.5.8</span> Model Building Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Building and Assessing Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-outcomes" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h3>
<p><strong>Conceptual Learning Outcomes</strong><br>
24. State the assumptions of the normal error regression model and check their validity using residual plots, qq plots, and other information.<br>
25. Interpret regression coefficients in models involving log transformations.<br>
26. Calculate predicted values for models involving log transformations.<br>
27. Interpret regression coefficient estimates on models with interaction terms.<br>
28. Calculate predicted values for models with interaction terms.<br>
29. Draw conclusions about models involving polynomial terms and interactions based on graphical representations of data.<br>
30. Identify instances of confounding and Simpson’s paradox and draw conclusions in these situations.<br>
31. Explain how multicollinearity impacts predictions and confidence/prediction intervals.<br>
32. Determine whether it is appropriate to add terms to a model using information such as <span class="math inline">\(R^2\)</span>, F-statistic, residual plots, correlation, and other visual representations.</p>
<p><strong>Computational Learning Outcomes</strong><br>
I. Build regression models involving nonlinear terms and interactions in R.</p>
</section>
<section id="regression-assumptions-checks" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="regression-assumptions-checks"><span class="header-section-number">5.1</span> Regression Assumptions Checks</h2>
<p>We’ve seen that tests and intervals based on the normal error regression model depend on four assumptions. If these assumptions are not reasonable then the tests and intervals may not be reliable.</p>
<p>The statement <span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1}+ \ldots + \beta_pX_{ip} + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span> implies the following:</p>
<ol type="1">
<li><p>Linearity: the expected value of <span class="math inline">\(Y\)</span> is a linear function of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>. (This assumption is only relevant for models including at least one quantitative explanatory variable.)</p></li>
<li><p>Normality: Given the values of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, <span class="math inline">\(Y\)</span> follows a normal distribution.</p></li>
<li><p>Constant Variance: Regardless of the values of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, the variance (or standard deviation) in the normal distribution for <span class="math inline">\(Y\)</span> is the same.</p></li>
<li><p>Independence: The response value for each observation is not affected by any of the other observations (expect due to explanatory variables included in the model).</p></li>
</ol>
<p><strong>Illustration of Model Assumptions</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SLR_Model_Assumptions.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>We know that these assumptions held true in the ice cream example, because we generated the data in a way that was consistent with these.</p>
<p>In practice, we will have only the data, without knowing the exact mechanism that produced it. We should only rely on the t-distribution based p-values and confidence intervals in the R output if these appear to be reasonable assumptions.</p>
<p>Of course, these assumptions will almost never be truly satisfied, but they should at least be a reasonable approximation if we are to draw meaningful conclusions.</p>
<section id="residual-diagnostic-plots" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="residual-diagnostic-plots"><span class="header-section-number">5.1.1</span> Residual Diagnostic Plots</h3>
<p>The following plots are useful when assessing the appropriateness of the normal error regression model.</p>
<ol type="1">
<li><p>Scatterplot of residuals against predicted values</p></li>
<li><p>Histogram of standardized residuals</p>
<ul>
<li>heavy skewness indicates a problem with normality assumption</li>
</ul></li>
<li><p>Normal quantile plot</p>
<ul>
<li>severe departures from diagonal line indicate problem with normality assumption</li>
</ul></li>
</ol>
<p><strong>Residual vs Predicted Plots</strong></p>
<p>A residual vs predicted plot is useful for detecting issues with the linearity or constant variance assumption.</p>
<ul>
<li>curvature indicates a problem with linearity assumption<br>
</li>
<li>“funnel” or “megaphone” shape indicates problem with constant variance assumption</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>If there is only one explanatory variable, plotting the residuals against that variable reveals the same information as a residual vs predicted plot.</p>
<p><strong>Histogram of Residuals</strong></p>
<p>A histogram of the residuals is useful for assessing the normality assumption.</p>
<ul>
<li>Severe skewness indicates violation of normality assumption</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Normal Quantile-Quantile (QQ) Plot</strong></p>
<p>Sometimes histograms can be inconclusive, especially when sample size is smaller.</p>
<p>A Normal quantile-quantile plot displays quantiles of the residuals against the expected quantiles of a normal distribution.</p>
<ul>
<li>Severe departures from diagonal line indicate a problem with normality assumption.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Checking Model Assumptions - Independence</strong></p>
<p>The independence assumption is often difficult to assess through plots, because there are many different ways in which independence could be violation. One common type of independence violation is periodic (or seasonal) behavior. For example if a company’s sales peak in the same months every year, this would be seasonal behavior and would violate the independence assumption. If the data are listed in the order they are taken, we can plot residuals against index number (row of the dataset) and check whether there are any patterns.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Unlike with the other assumptions, checking the residual vs.&nbsp;index plot does not catch all types of independence violations. First, it is only useful if the data are listed by date (or location) they occurred. The independence assumption can also be violated in other ways that a residual vs index plot will not catch.</p>
<p>Anything that causes some observations to be more alike than others for reasons other than the explanatory variables in the model would cause a violation of the independence assumption.</p>
<p>For example:</p>
<ol type="1">
<li>People in the study who are related.<br>
</li>
<li>Some plants grown in the same greenhouse and others in different greenhouses.<br>
</li>
<li>Some observations taken in same time period and others at different times.</li>
</ol>
<p>It is important to use your knowledge about the data and how it was collected, in addition to plots when assessing the independence assumption.</p>
<p>When the independence assumption is violated we need to use more advanced kinds of statistical models, beyond the ordinary regression model, in order to properly analyze the data.</p>
<section id="summary-of-checks-for-model-assumptions" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="summary-of-checks-for-model-assumptions">Summary of Checks for Model Assumptions</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Model assumption</th>
<th>How to detect violation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Curvature in residual plot</td>
</tr>
<tr class="even">
<td>Constant Variance</td>
<td>Funnel shape in residual plot</td>
</tr>
<tr class="odd">
<td>Normality</td>
<td>Skewness in histogram of residuals or departure from diag. line in QQ plot</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>Residual vs index plot and info about data collection</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="example-n-v-s-lakes" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="example-n-v-s-lakes"><span class="header-section-number">5.1.2</span> Example: N v S Lakes</h3>
<p>Recall our sample of 53 Florida Lakes, 33 in the north, and 20 in the south.</p>
<p><span class="math inline">\(\text{Mercury}_i = \beta_0 + \beta_1\times{\text{South}_i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0, \sigma)\)</span>.</p>
<p>When we use the normal error regression model, we are assuming the following:</p>
<ol type="1">
<li><p>Linearity: there is an expected mercury concentration for lakes in North Florida, and another for lakes in South Florida.</p></li>
<li><p>Normality: mercury concentrations of individual lakes in the north are normally distributed, and so are mercury concentrations in the south. These normal distributions might have different means.</p></li>
<li><p>Constant Variance: the normal distribution for mercury concentrations in North Florida has the same standard deviation as the normal distribution for mercury concentrations in South Florida</p></li>
<li><p>Independence: no two lakes are any more alike than any others, except for being in the north or south, which we account for in the model. We might have concerns about this, do to some lakes being geographically closer to each other than others.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>The <code>resid_panel</code> function in the <code>ggResidpanel</code> package produces the four plots shown above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(<span class="at">model =</span> M_Lakes_merc_loc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Notice that we see two lines of predicted values and residuals. This makes sense since all lakes in North Florida will have the same predicted value, as will all lakes in Southern Florida.</p>
<p>There appears to be a little more variability in residuals for Southern Florida (on the right), than Northern Florida, causing some concern about the constant variance assumption.</p>
<p>Overall, though, the assumptions seem mostly reasonable.</p>
<p>We shouldn’t be concerned about using theory-based hypothesis tests or confidence intervals for the mean mercury level or difference in mean mercury levels. There might be some concern that prediction intervals could be either too wide or too narrow, but this is not a major concern, since the constant variance assumption is not severe.</p>
</section>
<section id="example-ph-model" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="example-ph-model"><span class="header-section-number">5.1.3</span> Example: pH Model</h3>
<p>Recall the regression line estimating the relationship between a lake’s mercury level and pH.</p>
<p><span class="math inline">\(\text{Mercury}_i = \beta_0 + \beta_1\times\text{pH}_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0, \sigma)\)</span>.</p>
<p>The model assumes:</p>
<ol type="1">
<li><p>Linearity: the expected mercury level of a lake is a linear function of pH.</p></li>
<li><p>Normality: for any given pH, the mercury levels of lakes with that pH follow a normal distribution. For example, mercury levels for lakes with pH of 6 is are normally distributed, and mercury levels for lakes with pH of 9 are normally distributed, though these normal distributions may have different means.</p></li>
<li><p>Constant Variance: the variance (or standard deviation) in the normal distribution for mercury level is the same for each pH. For example, there is the same amount of variability associated with lakes with pH level 6, as pH level 8.</p></li>
<li><p>Independence: no two lakes are any more alike than any others, except with respect to pH, which is accounted for in the model. This may not be a reasonable assumption, but it’s unclear what the effects of such a violation would be.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>The plots for checking these assumptions are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(<span class="at">model =</span> M_Lakes_merc_pH, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The residual vs predicted plot does not show any linear trend, and variability appears to be about the same for low predicted values as for high ones. Thus, the linearity and constant variance assumptions appear reasonable.</p>
<p>The histogram shows some right-skewness, and the right-most points on the normal-qq plot are above the line, indicating a possible concern with the normality assumption. There is some evidence of right-skewness, which might impact the appropriateness of the normal error regression model.</p>
<p>We saw that the confidence interval and p-value associated with <span class="math inline">\(b_1\)</span> when we used theory-based formulas was similar to those we obtained using simulation. Normality violations can, but don’t always have a heavy impact on intervals associated with model coefficients. They do, however, lead to unreliable intervals for an expected response (i.e.&nbsp;the average mercury level in lakes with a pH of 7), and cause prediction intervals to be especially unreliable.</p>
</section>
<section id="example-house-prices" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="example-house-prices"><span class="header-section-number">5.1.4</span> Example: House Prices</h3>
<p>Recall the model for estimating price of a house, using size, waterfront status, and an interaction term.</p>
<p><span class="math inline">\(\text{Price}_i = \beta_0 + \beta_1\text{Sq.Ft.}_{i}+ \beta_2\text{Waterfront}_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>The model assumes:</p>
<ol type="1">
<li><p>Linearity: The expected price of a house is a linear function of its size. Waterfront houses may be priced higher or lower than non-waterfront houses, but both types increase at the same rate with respect to size.</p></li>
<li><p>Normality: Prices of houses of a given size and waterfront status are normally distributed.</p></li>
<li><p>Constant Variance: The variance (or standard deviation) in the normal distribution for prices is the same for all sizes and waterfront statuses.</p></li>
<li><p>Independence: No two houses are any more alike than any others, except with respect to size and waterfront status.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>Several reasons come to mind that might cause us to doubt the validity of these assumptions, but let’s investigate them empirically, using our data on 200 houses in the dataset.</p>
<p>The plots for checking these assumptions are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(<span class="at">model =</span> M_House_price_sqft_wf, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The plots reveal several concerns. In the residual plot, there is some sign of a nonlinear trend, though this is not too severe. Of greater concern is the megaphone shape, as we see much more vertical spread in residuals for houses with higher predicted prices on the right side of the graph than for ones with lower predicted prices on the left.</p>
<p>The Q-Q plot also raises concerns about normality. There is a tail above the diagonal line on the right side of the plot, and a smaller one below the line on the left side. These indicate that the most expensive houses tend to be more expensive than we would expect using a normal model, and the least expensive houses tend to be less expensive than expected. It’s not unusual to have a few outliers deviate from the diagonal line on either end of the QQ-plot. The histogram of residuals does generally show a symmetric, bell-shaped, pattern and most of the points do follow the line closely so the normality concern may not be too serious.</p>
<p>The index plot does not raise any concerns, but we might still have some concerns about independence. For example, houses in the same neighborhood might be more similarly priced than houses in different neighborhoods.</p>
</section>
<section id="impact-of-model-assumption-violations" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="impact-of-model-assumption-violations"><span class="header-section-number">5.1.5</span> Impact of Model Assumption Violations</h3>
<p>In this chapter, we’ve studied the normal error regression model and its underlying assumptions. We’ve seen that when these assumptions are realistic, we can use distributions derived from probability theory, such as t and F distributions to approximate sampling distributions, in place of the simulation-based methods seen in Chapters 3 and 4.</p>
<p>Of course, real data don’t come exactly from processes like the fictional ice cream dispenser described in Section 4.1, so it’s really a question of whether this model is a realistic approximation (or simplification) of the true mechanism that led to the data we observe. We can use diagnostics like residual and Normal-QQ plots, as well as our intuition and background knowledge to assess whether the normal error regression model is a reasonable approximation.</p>
<p>The p-values provided by the <code>lm</code> summary output, and <code>anova</code> commands, and the and intervals produced by the <code>confint</code>, and <code>predict</code> command, as well as many other R commands, depend on the assumptions of the normal error regression model, and should only be used when these assumptions are reasonable.</p>
<p>In situations where some model assumptions appear to be violated, we might be okay using certain tests/intervals, but not others. In general, we should proceed with caution in these situations.</p>
<p>The table below provides guidance on the potential impact of model assumption violation on predicted values, confidence intervals, and prediction intervals.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model assumption Violated</th>
<th>Predicted Values</th>
<th>Confidence Intervals</th>
<th>Prediction Intervals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Unreliable</td>
<td>Unreliable</td>
<td>Unreliable</td>
</tr>
<tr class="even">
<td>Constant Variance</td>
<td>Reliable</td>
<td>Somewhat unreliable - Some too wide, others too narrow</td>
<td>Very unreliable - Some too wide, others too narrow</td>
</tr>
<tr class="odd">
<td>Normality</td>
<td>Reliable</td>
<td>Possibly unreliable - might be symmetric when they shouldn’t be. Might be okay when skewness isn’t bad and sample size is large.</td>
<td>Very unreliable - will be symmetric when they shouldn’t be</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>might be reliable</td>
<td>unreliable - either too wide or too narrow</td>
<td>unreliable - either too wide or too narrow</td>
</tr>
</tbody>
</table>
<p>When model assumptions are a concern, consider a using a transformation of the data, a more advanced model, or a more flexible technique, such as a nonparametric approach or statistical machine learning algorithm.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="transformations" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="transformations"><span class="header-section-number">5.2</span> Transformations</h2>
<p>When there are violations of model assumptions, we can sometimes correct for these by modeling a a function of the response variable, rather than the response variable itself. When the histogram of residuals and normal qq plot show signs of right-skewness, modeling a logarithm of the response variable is often helpful.</p>
<section id="example-modeling-car-prices" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="example-modeling-car-prices"><span class="header-section-number">5.2.1</span> Example: Modeling Car Prices</h3>
<p>We’ll work with data on a set of 110 new cars, released in 2020. The data come from the <code>LockData5</code> package in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Lock5Data)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Cars2020)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>Cars2020 <span class="ot">&lt;-</span> Cars2020 <span class="sc">|&gt;</span> <span class="fu">rename</span>(<span class="at">Price =</span> LowPrice) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Make, Model, Price, Acc060, <span class="fu">everything</span>() ) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>HighPrice)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Cars2020)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Make Model Price Acc060   Type CityMPG HwyMPG Seating Drive Acc030 QtrMile
1 Acura   MDX  44.4    6.8    SUV      14     31       7   AWD    2.8    15.3
2 Acura   RLX  54.9    6.5  Sedan      15     36       5   AWD    2.7    15.0
3  Audi    A3  33.3    8.3  Sedan      18     40       5   AWD    3.2    16.4
4  Audi    A4  37.4    6.3 Sporty      18     40       5   AWD    2.7    14.9
5  Audi    A6  54.9    6.8  Sedan      17     39       5   AWD    2.8    15.3
6  Audi    A8  83.8    6.1  Wagon      20     27       5   AWD    2.4    14.5
  Braking FuelCap Length Width Height Wheelbase UTurn Weight     Size
1     135    19.5    196    77     67       111    40   4200 Midsized
2     128    18.5    198    74     58       112    40   3930 Midsized
3     124    13.2    175    70     56       104    37   3135    Small
4     135    15.3    186    73     56       111    40   3630    Small
5     129    19.3    195    74     57       115    38   4015 Midsized
6     133    21.7    209    77     59       123    43   4810    Large</code></pre>
</div>
</div>
<p>We’ll begin by examining the relationship between price (in thousands) and the amount of time it takes a car to accelerate from 0 to 60 mph (Acc060).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>Acc060, <span class="at">y=</span>Price)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> Cars2020 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Price <span class="sc">&gt;</span> <span class="dv">80</span> <span class="sc">|</span> Acc060 <span class="sc">&lt;</span> <span class="dv">5</span>), </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">label=</span>Model), <span class="at">nudge_y=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="at">data =</span> Cars2020 <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">filter</span>(Model<span class="sc">==</span><span class="st">"Spark"</span>), <span class="fu">aes</span>(<span class="at">label=</span>Model), <span class="at">nudge_y=</span><span class="dv">3</span>, <span class="at">nudge_x=</span><span class="sc">-</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_text</span>(<span class="at">data =</span> Cars2020 <span class="sc">|&gt;</span> <span class="fu">filter</span>(Model<span class="sc">==</span><span class="st">"Mirage"</span>), <span class="fu">aes</span>(<span class="at">label=</span>Model), </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">nudge_y=</span><span class="dv">3</span>, <span class="at">nudge_x=</span><span class="fl">0.3</span>) <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>We’ll look at the assumptions associated with the model for predicting car price, using acceleration time as the explanatory variable.</p>
<p>We fit a model of the form</p>
<p><span class="math display">\[
\text{Price} = \beta_0 +\beta_1 \times\text{Acc060} + \epsilon_i, \text{where } \epsilon_i\sim\mathcal{N}(0, \sigma)
\]</span></p>
<p>We fit the model in R and display the summary below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>M_Cars_price_acc060 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, Price<span class="sc">~</span>Acc060)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars_price_acc060)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Acc060, data = Cars2020)

Residuals:
    Min      1Q  Median      3Q     Max 
-33.895  -7.410  -1.172   4.947  52.280 

Coefficients:
            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)  90.0583     6.2721  14.359 &lt; 0.0000000000000002 ***
Acc060       -7.0826     0.7851  -9.021   0.0000000000000078 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.85 on 108 degrees of freedom
Multiple R-squared:  0.4297,    Adjusted R-squared:  0.4244 
F-statistic: 81.37 on 1 and 108 DF,  p-value: 0.000000000000007802</code></pre>
</div>
</div>
<p>The most relevant estimate here is <span class="math inline">\(b_1=\)</span>-7.08, which tells us that for each additional second it takes to accelerate from 0 to 60 mph, we estimate price of a car to decrease by about 7 thousand dollars. A confidence interval for this expected decrease is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(M_Cars_price_acc060, <span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm=</span><span class="st">"Acc060"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           2.5 %    97.5 %
Acc060 -8.638874 -5.526288</code></pre>
</div>
</div>
<p>Before we draw conclusions from this model, however, we should check the assumptions associated with it. The assumptions are:</p>
<ol type="1">
<li><p>Linearity: There is a linear relationship between the price of a car and the amount of time it takes to accelerate from 0 to 60 mph.</p></li>
<li><p>Normality: For a given acceleration time, prices of cars are normally distributed.</p></li>
<li><p>Constant Variance: The amount of variability in car prices is the same, for all acceleration times.</p></li>
<li><p>Independence: No two car prices are any more alike than any others for any reason other than acceleration time.</p></li>
</ol>
<p>Diagnostic plots are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(M_Cars_price_acc060, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>There is a funnel-shape in the residual plot, indicating a concern about the constant variance assumption. There appears to be more variability in prices for more expensive cars than for cheaper cars. There is also some concern about the normality assumption, as the histogram and QQ plot indicate slight right-skewness, though it is not too severe.</p>
</section>
<section id="log-transformation" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="log-transformation"><span class="header-section-number">5.2.2</span> Log Transformation</h3>
<p>When residual plots yield model inadequacy, we might try to correct these by applying a transformation to the response variable.</p>
<p>When working a nonnegative, right-skewed response variable, it is often helpful to work with the logarithm of the response variable.</p>
<p>Note: In R, <code>log()</code> denotes the natural (base e) logarithm, often denoted <code>ln()</code>. We can actually use any logarithm, but the natural logarithm is commonly used.</p>
<p>The <code>log(Price)</code> for the first 6 rows of the data are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Cars2020 <span class="ot">&lt;-</span> Cars2020 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">LogPrice =</span> <span class="fu">log</span>(Price)) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Cars2020 <span class="sc">|&gt;</span> <span class="fu">select</span>(Model, Make, Price, LogPrice, Acc060) <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Model  Make Price LogPrice Acc060
1   MDX Acura  44.4 3.793239    6.8
2   RLX Acura  54.9 4.005513    6.5
3    A3  Audi  33.3 3.505557    8.3
4    A4  Audi  37.4 3.621671    6.3
5    A6  Audi  54.9 4.005513    6.8
6    A8  Audi  83.8 4.428433    6.1</code></pre>
</div>
</div>
<p>We’ll use the model:</p>
<p><span class="math display">\[
\text{Log Price} = \beta_0 + \beta_1\times \text{Acc060} + \epsilon_i , \text{ where } \epsilon_i\sim\mathcal{N}(0, \sigma)
\]</span></p>
<p>The plot shows log(price) on the y-axis. We see that the relationship appears more linear than when we plot price itself.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>Acc060, <span class="at">y=</span><span class="fu">log</span>(Price))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Acceleration Time"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Log of Price"</span>) <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Acceleration Time and Log Price"</span>) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>We fit the model using <code>log(Price)</code> as the response variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>M_Cars_logprice_acc060 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars_logprice_acc060)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.90992 -0.19686  0.00148  0.15566  0.63774 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)  5.00390    0.14547   34.40 &lt;0.0000000000000002 ***
Acc060      -0.19889    0.01821  -10.92 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.298 on 108 degrees of freedom
Multiple R-squared:  0.5248,    Adjusted R-squared:  0.5204 
F-statistic: 119.3 on 1 and 108 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Before interpreting the coefficients, we’ll check the residual plots for the log model.</p>
<p><strong>Assumption Check for Model on Log Price</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(M_Cars_logprice_acc060, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>There is still some concern about constant variance, though perhaps not as much as before. The normality assumption appears more reasonable.</p>
<p>We’ll proceed, noting that the slight concern about constant variance might raise questions about confidence intervals for an expected response, and especially prediction intervals.</p>
</section>
<section id="inference-for-log-model" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="inference-for-log-model"><span class="header-section-number">5.2.3</span> Inference for Log Model</h3>
<p>The estimated regression equation is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{LogPrice}} &amp; = 5.0039 + -0.1989 \times \text{Acc060}
\end{aligned}
\]</span> Thus,</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{Price}} &amp; = e^{5.0039 + -0.1989 \times \text{Acc060}}
\end{aligned}
\]</span></p>
<p>Predicted price for car that takes 7 seconds to accelerate:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{Price}} &amp; = e^{5.0039 + -0.1989 \times 7}
\end{aligned}
\]</span></p>
<p>Predicted price for car that takes 10 seconds to accelerate:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{Price}} &amp; = e^{5.0039 + -0.1989 \times 10}
\end{aligned}
\]</span></p>
<p>When using the <code>predict</code> command, R gives predictions are for log(Price), so we need to exponentiate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#predicted log of price</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1 
3.61169 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
37.02859 </code></pre>
</div>
</div>
<p>A car that accelerates from 0 to 60 mph in 7 seconds is expected to cost about 37 thousand dollars.</p>
</section>
<section id="log-model-interpretations" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="log-model-interpretations"><span class="header-section-number">5.2.4</span> Log Model Interpretations</h3>
<p>When we use a model with a log transformation of the response variable, our interpretations of the response variable change. Let’s look at some algebra that will help us see how to interpret the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in this situation.</p>
<p><span class="math display">\[
\begin{aligned}
\text{Log of Expected Price} &amp; = \beta_0 + \beta_1\times \text{Acc060}\  \text{, Thus:} \\
\text{ Expected Price} &amp; = e^{\beta_0 + \beta_1\times \text{Acc060} } \\
&amp; e^{\beta_0}e^{\beta_1 \times \text{Acc060}} \\
&amp; e^{\beta_0}(e^{\beta_1})^\text{Acc060}
\end{aligned}
\]</span></p>
<ul>
<li><p>We see that when <span class="math inline">\(\text{Acc060}=0\)</span>, the expected price is <span class="math inline">\(e^{\beta_0}\)</span>. So, <span class="math inline">\(e^{\beta_0}\)</span> is theoretically the expected price of a car that can accelerate from 0 to 60 mph in no time, but this is not a meaningful interpretation.</p></li>
<li><p>We see that for each additional second it takes to accelerate from 0 to 60 mph, the exponent on <span class="math inline">\(e^{\beta_1}\)</span>, increases by one, meaning price is expected to multiply by an additional <span class="math inline">\(e^{\beta_1}\)</span>. <strong>For each additional second it takes a car to accelerate, price is expected to multiply by a factor of</strong> <span class="math inline">\(e^{b_1}\)</span>.</p></li>
</ul>
<p>We calculate <span class="math inline">\(e^{b_0}\)</span> and <span class="math inline">\(e^{b_1}\)</span> in R, and interpret the estimates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(M_Cars_logprice_acc060<span class="sc">$</span>coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      Acc060 
148.9925267   0.8196429 </code></pre>
</div>
</div>
<ul>
<li>For each additional second in acceleration time, price is expected to multiply by a a factor of <span class="math inline">\(e^{-0.1989}\)</span> = 0.82. Thus, each 1-second increase in acceleration time is estimated to be associated with a 18% drop in price, on average.</li>
</ul>
<p><strong>Confidence Interval for <span class="math inline">\(e^{\beta_1}\)</span></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(M_Cars_logprice_acc060, <span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm=</span><span class="st">"Acc060"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           2.5 %    97.5 %
Acc060 0.7905858 0.8497679</code></pre>
</div>
</div>
<ul>
<li>We are 95% confident that for each additional second in acceleration time, the price of a car multiplies by a factor between 0.79 and 0.85, an estimated decrease between 15 and 21 percent.</li>
</ul>
<p><strong>Log Model CI for Expected Response</strong></p>
<p>If we just use the <code>predict</code> function, we get a confidence interval for <code>log(price)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fit      lwr      upr
1 3.61169 3.547818 3.675563</code></pre>
</div>
</div>
<p>To get an interval for price itself, we exponentiate, using <code>exp</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"confidence"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 37.02859 34.73743 39.47087</code></pre>
</div>
</div>
<p>We are 95% confident that the mean price amoung all cars that accelerate from 0 to 60 mph in 7 seconds is between <span class="math inline">\(e^{3.55
} =\)</span> 34.7 and <span class="math inline">\(e^{3.68}=\)</span> 39.5 thousand dollars.</p>
<p><strong>Log Model Prediction Interval</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fit      lwr      upr
1 3.61169 3.017521 4.205859</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"prediction"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 37.02859 20.44056 67.07822</code></pre>
</div>
</div>
<p>We are 95% confident that the price for an individual car that accelerates from 0 to 60 mph in 7 seconds is between <span class="math inline">\(e^{3.02
} =\)</span> 20.4 and <span class="math inline">\(e^{4.21}=\)</span> 67.1 thousand dollars.</p>
</section>
<section id="model-comparisons" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="model-comparisons"><span class="header-section-number">5.2.5</span> Model Comparisons</h3>
<p>We’ll compare the intervals we obtain using the <code>log</code> transformation to those from the model without the transformation.</p>
<p><strong>95% Confidence interval for average price of cars that take 7 seconds to accelerate:</strong></p>
<p>Original Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars_price_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="dv">7</span>), <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 40.48028 37.72628 43.23428</code></pre>
</div>
</div>
<p>Transformed Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level=</span><span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 37.02859 34.73743 39.47087</code></pre>
</div>
</div>
<p><strong>95% Prediction interval for price of an individual car that takes 7 seconds to accelerate:</strong></p>
<p>Original Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars_price_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="dv">7</span>), <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit     lwr      upr
1 40.48028 14.8614 66.09916</code></pre>
</div>
</div>
<p>Transformed Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars_logprice_acc060, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fu">c</span>(<span class="dv">7</span>)), <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 37.02859 20.44056 67.07822</code></pre>
</div>
</div>
<p>Notice that the transformed interval is not symmetric and allows for a longer “tail” on the right than the left.</p>
</section>
<section id="log-model-visualization" class="level3" data-number="5.2.6">
<h3 data-number="5.2.6" class="anchored" data-anchor-id="log-model-visualization"><span class="header-section-number">5.2.6</span> Log Model Visualization</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The log model suggests an nonlinear trend in price with respect to acceleration time and gives wider confidence and prediction intervals for cars that accelerate faster and tend to be more expensive. It also gives non-symmetric intervals. These results appear to be consistent with the observed data.</p>
</section>
<section id="comments-on-transformations" class="level3" data-number="5.2.7">
<h3 data-number="5.2.7" class="anchored" data-anchor-id="comments-on-transformations"><span class="header-section-number">5.2.7</span> Comments on Transformations</h3>
<p>Violations of model assumptions often come from right skewness, which is especially common in economic and financial data. Log transformations are often helpful in fitting models to such data. Log models are also easily interpretable, allowing us to interpret estimates as percent change.</p>
<p>We could have used another transformation, such as <span class="math inline">\(\sqrt{\text{Price}}\)</span>, and in some cases, other transformations might better correct for violations of model assumptions. That said, other transformations are harder to interpret than the log transformation. It is important to think about both the appropriateness of our model assumptions as well as how easily we will be able to interpret and explain our conclusions when choosing a transformation.</p>
<p>In this section, we looked at a transformation involving a single quantitative explanatory variable.</p>
<p>If the explanatory variable is categorical:<br>
</p>
<ul>
<li><span class="math inline">\(e^{\beta_0}\)</span> represents the expected response in the baseline category<br>
</li>
<li><span class="math inline">\(e^{\beta_j}\)</span> represents the number of times larger the expected response in category <span class="math inline">\(j\)</span> is, compared to the baseline category.</li>
</ul>
<p>When working with multiple regression models, it is still important to mention holding other variables constant when interpreting parameters associated with one of the variables.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="polynomial-regression" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="polynomial-regression"><span class="header-section-number">5.3</span> Polynomial Regression</h2>
</section>
<section id="models-with-interaction" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="models-with-interaction"><span class="header-section-number">5.4</span> Models with Interaction</h2>
<section id="definition-of-interaction" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="definition-of-interaction"><span class="header-section-number">5.4.1</span> Definition of Interaction</h3>
<p>In Chapter 2, we modeled the price of a house in King County, Washington, using its size in square feet, and whether or not it was on the waterfront as explanatory variable. We used a multiple regression model of the form</p>
<p><span class="math display">\[
\widehat{Price} = b_0 + b_1\times\text{SqFt} + b_2\times\text{Waterfront}
\]</span></p>
<p>Recall that this model assumes the slope relating price and square footage is the same (<span class="math inline">\(b_1\)</span>) for houses on the waterfront as for houses not on the waterfront. An illustration of the model is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Plot_House_price_sqft_wf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This assumption of the rate of change in price with respect to living space being the same for waterfront houses, as for non-waterfront houses might be unrealistic.</p>
<p>Let’s fit separate lines for waterfront and non-waterfront houses, without requiring them to have the same slope.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">x=</span>sqft_living, <span class="at">y=</span>price, <span class="at">color=</span>waterfront)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It appears that the prices of the houses on the waterfront are increasing more rapidly, with respect to square feet of living space, than the non-waterfront houses. The effect of additional square feet on the price of the house appears to depend on whether or not the house is on the waterfront. This is an example of an <strong>interaction</strong> between square footage and waterfront status.</p>
<p>An <strong>interaction</strong> between two explanatory variables occurs when the effect of one explanatory variable on the response depends on the other explanatory variable.</p>
</section>
<section id="interaction-term" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="interaction-term"><span class="header-section-number">5.4.2</span> Interaction Term</h3>
<p>If we want to allow for different slopes between waterfront and non-waterfront houses, we’ll need to change the mathematical equation of our model. To do that, we’ll add a coefficient <span class="math inline">\(b_3\)</span>, multiplied by the product of our two explanatory variables.</p>
<p>The model equation is</p>
<p><span class="math display">\[
\widehat{Price} = b_0 + b_1\times\text{Sq. Ft.} + b_2\times\text{waterfront} + b_3\times\text{Sq.Ft}\times\text{Waterfront}
\]</span></p>
<p>The last term is called an <strong>interaction term.</strong></p>
<p>For a house on the waterfront (<span class="math inline">\(\text{waterfront}=1\)</span>), the equation relating price to square feet is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = b_0 + b_1\times\text{Sq. Ft.} + b_2\times\text{1} + b_3\times\text{Sq.Ft}\times\text{1} \\
&amp; = (b_0+b_2) + (b_1+b_3)\times{\text{Sq. Ft.}}
\end{aligned}
\]</span> For a house not on the waterfront (<span class="math inline">\(\text{waterfront}=0\)</span>), the equation relating price to square feet is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = b_0 + b_1\times\text{Sq. Ft.} + b_2\times\text{0} + b_3\times\text{Sq.Ft}\times\text{0} \\
&amp; = b_0 + b_1\times{\text{Sq. Ft}}
\end{aligned}
\]</span></p>
<p>The intercept is <span class="math inline">\(b_0\)</span> for non-waterfront houses, and <span class="math inline">\(b_0 + b_2\)</span> for waterfront houses.</p>
<p>The slope is <span class="math inline">\(b_1\)</span> for non-waterfront houses, and <span class="math inline">\(b_1 + b_3\)</span> for waterfront houses.</p>
<p>Thus, the model allows both the slope and intercept to differ between waterfront and non-waterfront houses.</p>
</section>
<section id="interaction-models-in-r" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="interaction-models-in-r"><span class="header-section-number">5.4.3</span> Interaction Models in R</h3>
<p>To fit an interaction model in R, use <code>*</code> instead of <code>+</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>M_House_price_sqft_wf_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price<span class="sc">~</span>sqft_living<span class="sc">*</span>waterfront)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_House_price_sqft_wf_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ sqft_living * waterfront, data = Houses)

Residuals:
     Min       1Q   Median       3Q      Max 
-1474.37  -151.07   -31.29   106.77  1331.87 

Coefficients:
                            Estimate Std. Error t value             Pr(&gt;|t|)
(Intercept)               -114.37347   59.00418  -1.938                0.054
sqft_living                  0.30987    0.02496  12.417 &lt; 0.0000000000000002
waterfrontYes              -90.11528  168.67011  -0.534                0.594
sqft_living:waterfrontYes    0.27292    0.04856   5.620          0.000000065
                             
(Intercept)               .  
sqft_living               ***
waterfrontYes                
sqft_living:waterfrontYes ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 322.8 on 196 degrees of freedom
Multiple R-squared:  0.7771,    Adjusted R-squared:  0.7737 
F-statistic: 227.7 on 3 and 196 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>House_Int_b0 <span class="ot">&lt;-</span> M_House_price_sqft_wf_int<span class="sc">$</span>coef[<span class="dv">1</span>] <span class="sc">|&gt;</span><span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>House_Int_b1 <span class="ot">&lt;-</span> M_House_price_sqft_wf_int<span class="sc">$</span>coef[<span class="dv">2</span>] <span class="sc">|&gt;</span><span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>House_Int_b2 <span class="ot">&lt;-</span> M_House_price_sqft_wf_int<span class="sc">$</span>coef[<span class="dv">3</span>] <span class="sc">|&gt;</span><span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>House_Int_b3 <span class="ot">&lt;-</span> M_House_price_sqft_wf_int<span class="sc">$</span>coef[<span class="dv">4</span>] <span class="sc">|&gt;</span><span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The regression equation is</p>
<p><span class="math display">\[
\widehat{Price} = -114.37 + 0.31\times\text{Sq. Ft.}  + -90.12\times\text{waterfront} + 0.27\times\text{Sq.Ft}\times\text{Waterfront}
\]</span></p>
<p>For a house on the waterfront (<span class="math inline">\(\text{waterfront}=1\)</span>), the equation is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = -114.37 + 0.31\times\text{Sq. Ft.} -90.12 \times\text{1} + 0.27\times\text{Sq.Ft}\times\text{1} \\
&amp; = (-114.37 - -90.12) + (0.31+0.27)\times{\text{Sq. Ft.}} \\
&amp; = -204.49 + `House_Int_b1 + House_Int_b3`\times{\text{Sq. Ft.}}
\end{aligned}
\]</span></p>
<p>For a house not on the waterfront (<span class="math inline">\(\text{waterfront}=0\)</span>), the equation is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Price} &amp; = -114.37 + 0.31\times\text{Sq. Ft.} -90.12 \times\text{0} + 0.27\times\text{Sq.Ft}\times\text{0} \\
&amp; = -114.37 + 0.31\times{\text{Sq. Ft.}}
\end{aligned}
\]</span> <strong>Interpretation</strong></p>
<p>When interpreting <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, we need to state that the interpretations apply only to the “baseline” category (in this case non-waterfront houses).</p>
<p>In a model with interaction, it does not make sense to talk about holding one variable constant when interpreting the effect of the other, since the effect of one variable depends on the value or category of the other. Instead, we must state the value or category of one variable when interpreting the effect of the other.</p>
<p><strong>Interpretations:</strong></p>
<ul>
<li><p><span class="math inline">\(b_0\)</span> - On average, a house with 0 square feet that is not on the waterfront is expected to cost -114.37 thousand dollars. This is not a sensible interpretation since there are no houses with 0 square feet.</p></li>
<li><p><span class="math inline">\(b_1\)</span> - For each additional square foot in size, the price of a non-waterfront house is expected to increase by 0.31 thousand dollars.</p></li>
<li><p><span class="math inline">\(b_2\)</span> - On average, the price of a waterfront house with 0 square feet is expected to be -90.12 thousand dollars less than the price of a non-waterfront house with 0 square feet. This is not a sensible interpretation in this case.</p></li>
<li><p><span class="math inline">\(b_3\)</span> - For each additional square foot in size, the price of a waterfront house is expected to increase by 0.27 thousand dollars more than a non-waterfront house.</p></li>
</ul>
<p>Alternatively, we could interpret <span class="math inline">\(b_0+b_2\)</span> and <span class="math inline">\(b_1+b_3\)</span> together.</p>
<ul>
<li><p><span class="math inline">\(b_0 + b_2\)</span> - On average, a house with 0 square feet that is on the waterfront is expected to cost -204.49 thousand dollars. This is not a sensible interpretation since there are no houses with 0 square feet.</p></li>
<li><p><span class="math inline">\(b_1 + b_3\)</span> - For each additional square foot in size, the price of a waterfront house is expected to increase by 0.58 thousand dollars.</p></li>
</ul>
<p><strong>Prediction</strong></p>
<p>We calculate predicted prices for the following houses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Houses[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">16</span>), ] <span class="sc">%&gt;%</span> <span class="fu">select</span>(ID, price, sqft_living, waterfront)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
     ID price sqft_living waterfront
  &lt;int&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;     
1    90  335.        1030 No        
2  2141 1700         2500 Yes       </code></pre>
</div>
</div>
<p><span class="math display">\[
\widehat{Price}_1 =  -114.37 + 0.31\times 1030  + -90.12\times0 + 0.27\times 1030 \times 0 = FALSE \text{ thousand dollars}
\]</span></p>
<p><span class="math display">\[
\widehat{Price}_1 =  -114.37 + 0.31\times 1030  + -90.12\times1 + 0.27\times 1030 \times 1 = 392.91 \text{ thousand dollars}
\]</span></p>
</section>
<section id="variability-explained" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="variability-explained"><span class="header-section-number">5.4.4</span> Variability Explained</h3>
<p>We’ll calculate <span class="math inline">\(R^2\)</span> for the model with the interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_House_price_sqft_wf_int)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7770731</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_House_price_sqft_wf)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7411526</code></pre>
</div>
</div>
<p>We see that adding an interaction term improved the proportion of variability in house price explained by the model from 0.78 to 0.7411526. This is a fairly notable increase.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M_House_price_sqft_wf, M_House_price_sqft_wf_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: price ~ sqft_living + waterfront
Model 2: price ~ sqft_living * waterfront
  Res.Df      RSS Df Sum of Sq      F        Pr(&gt;F)    
1    197 23720774                                      
2    196 20429024  1   3291749 31.582 0.00000006502 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="considerations-for-using-interactions" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="considerations-for-using-interactions"><span class="header-section-number">5.4.5</span> Considerations for Using Interactions</h3>
<p>It might be tempting to think we should always add an interaction term to a model when using two or more explanatory variables. After all, an interaction term is just another term added to the model, meaning that <span class="math inline">\(R^2\)</span> will never go down.</p>
<p>Adding an interaction term is not always a good idea, though. We saw that doing so makes interpretations more complicated. Increasing the complexity of a model also increases the risk of overfitting, potentially hurting predictive performance on new data.</p>
<p>We should only add an interaction term if we have strong reason to believe that the rate of change in the response variable with respect to one explanatory variable really does depend on the other variable. This might come from background knowledge about the subject, or consultation with an expert in the area. It could also come from data visualization, and the increase in variability in the response variable explained when an interaction term is added to the model.</p>
<p>In the house price dataset, we might expect that the price of waterfront houses might increase more rapidly as they get bigger than the price of non-waterfront houses. The fact that the lines shown in the scatterplot are not close to being parallel provides further evidence of a difference in rate of increase, providing justification for the use of an interaction term in the model. Furthermore, <span class="math inline">\(R^2\)</span> increases notably (from 0.76 to 0.85), when an interaction term is added. All of these reasons support using an interaction term in this context.</p>
<p>When examining a scatterplot, we should note that even if there is truly no interaction among all houses, the lines probably won’t be exactly parallel, due to random deviations among the sample of houses chosen. If the lines are reasonably close to parallel, then an interaction term is likely not needed.</p>
<p>We’ll look more at criteria for determining whether to add an interaction term to a model in the coming sections.</p>
</section>
<section id="when-to-include-interaction" class="level3" data-number="5.4.6">
<h3 data-number="5.4.6" class="anchored" data-anchor-id="when-to-include-interaction"><span class="header-section-number">5.4.6</span> When to Include Interaction</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>Acc060, <span class="at">y=</span><span class="fu">log</span>(Price), <span class="at">color=</span>Drive)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">*</span> Drive))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 * Drive, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.67884 -0.17380  0.00747  0.17140  0.54195 

Coefficients:
                Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)      5.15099    0.16986  30.325 &lt; 0.0000000000000002 ***
Acc060          -0.20730    0.02197  -9.436  0.00000000000000122 ***
DriveFWD        -0.72581    0.38438  -1.888               0.0618 .  
DriveRWD        -1.37366    0.67884  -2.024               0.0456 *  
Acc060:DriveFWD  0.05225    0.04362   1.198               0.2337    
Acc060:DriveRWD  0.16158    0.12444   1.298               0.1970    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2618 on 104 degrees of freedom
Multiple R-squared:  0.6469,    Adjusted R-squared:  0.6299 
F-statistic: 38.11 on 5 and 104 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">x=</span>sqft_living, <span class="at">y=</span>price, <span class="at">color=</span>condition)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(<span class="at">data=</span>Houses, price <span class="sc">~</span> condition <span class="sc">*</span> sqft_living))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ condition * sqft_living, data = Houses)

Residuals:
     Min       1Q   Median       3Q      Max 
-1408.93  -217.83   -32.08   163.77  1858.38 

Coefficients:
                                 Estimate Std. Error t value
(Intercept)                    -389.16787   77.15235  -5.044
conditiongood                    -5.07017  163.36630  -0.031
conditionvery_good              202.14373  292.59452   0.691
sqft_living                       0.45644    0.02913  15.671
conditiongood:sqft_living         0.05326    0.06607   0.806
conditionvery_good:sqft_living    0.03863    0.12017   0.321
                                           Pr(&gt;|t|)    
(Intercept)                              0.00000104 ***
conditiongood                                 0.975    
conditionvery_good                            0.490    
sqft_living                    &lt; 0.0000000000000002 ***
conditiongood:sqft_living                     0.421    
conditionvery_good:sqft_living                0.748    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 414.3 on 194 degrees of freedom
Multiple R-squared:  0.6367,    Adjusted R-squared:  0.6273 
F-statistic: 67.99 on 5 and 194 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
</section>
<section id="interaction-vs-correlation" class="level3" data-number="5.4.7">
<h3 data-number="5.4.7" class="anchored" data-anchor-id="interaction-vs-correlation"><span class="header-section-number">5.4.7</span> Interaction vs Correlation</h3>
<p>It is easy to confuse the concept of interaction with that of correlation. These are, in fact, very different concepts.</p>
<p>A correlation between two variables means that as one increases, the other is more likely to increase or decrease. We only use the word correlation to describe two quantitative variables, but we could discuss the similar notion of a relationship between categorical variables.</p>
<p>An interaction between two explanatory variables means that the effect of one on the response depends on the other.</p>
<p><strong>Examples of Correlations (or relationships)</strong></p>
<ol type="1">
<li><p>Houses on the waterfront tend to be bigger than houses not on the waterfront, so there is a relationship between square feet and waterfront status.</p></li>
<li><p>Houses with large amounts of living space in square feet are likely to have more bedrooms, so there is a correlation between living space and bedrooms.</p></li>
<li><p>Suppose that some genres of movies (drama, comedy, action, etc.) tend to be longer than others. This is an example of a relationship between genre and length.</p></li>
</ol>
<p>The fact that there is a correlation between explanatory variables is NOT a reason to add an interaction term involving those variables in a model. Correlation is something entirely different than interaction!</p>
<p><strong>Examples of Interactions</strong></p>
<ol type="1">
<li><p>As houses on the waterfront increase in size, their price increases more rapidly than for houses not on the waterfront. This means there is an interaction between size and waterfront location.</p></li>
<li><p>Suppose that the effect of additional bedrooms on price is different for houses with lots of living space than for houses with little living space. This would be an example of an interaction between living space and number of bedrooms.</p></li>
<li><p>Suppose that audiences become more favorable to dramas as they get longer, but less favorable to comedies as they get longer. In this scenario, the effect of movie length on audience rating depends on the genre of the movie, indicating an interaction between length and genre.</p></li>
</ol>
</section>
</section>
<section id="building-a-model-for-interpretation" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="building-a-model-for-interpretation"><span class="header-section-number">5.5</span> Building a Model for Interpretation</h2>
<p>So far, we’ve dealt with models with 2 or fewer variables. Some real questions require accounting for more than two variables. In these situations, we’ll need to develop a model that is complex enough to capture the important aspects of the mechanism we’re modeling, but also simple enough for us to be able to explain and interpret. We’ll need to decide how many variables to include in the model, and whether to use transformations, or to include interaction terms.</p>
<p>We’ll examine strategies for modeling in two different contexts. In this chapter, we’ll focus on building models for situations when we want to make interpretations and draw conclusions about relationships between variables. In Chapter 7, we focus on modeling solely for the purpose of prediction, when we are not interested in making interpretations or conclusions about relationships between variables.</p>
<p>We’ll need to think about things like:</p>
<ul>
<li>which explanatory variables should we include in the model, and how many?<br>
</li>
<li>should we include any interaction terms?<br>
</li>
<li>should we use any nonlinear terms?<br>
</li>
<li>should we use a transformation of the response variable?</li>
</ul>
<p>In this section we’ll go through a set of steps to build a model that will help us understand factors that contribute to the price of a car.</p>
<section id="exploratory-data-analysis" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">5.5.1</span> Exploratory Data Analysis</h3>
<p>The Cars2020 dataset from the <code>Lock5Data</code> R package contains several variables with information pertaining to the price of a new 2020 car. These include:</p>
<ul>
<li><code>Make</code><br>
</li>
<li><code>Manufacturer</code> (e.g.&nbsp;Chevrolet, Toyota, etc.)<br>
</li>
<li><code>Model</code> - Car model (e.g.&nbsp;Impala, Highlander, …)<br>
</li>
<li><code>Type</code> - Vehicle category (Hatchback, Minivan, Sedan, Sporty, SUV, or Wagon)<br>
</li>
<li><code>Price</code> - Lowest MSRP (in $1,000)<br>
</li>
<li><code>CityMPG</code> - City miles per gallon (EPA)<br>
</li>
<li><code>HwyMPG</code> - Highway miles per gallon (EPA)<br>
</li>
<li><code>Seating</code> - Seating capacity<br>
</li>
<li><code>Drive</code> - Type of drive (AWD, FWD, or RWD)<br>
</li>
<li><code>Acc030</code> - Time (in seconds) to go from 0 to 30 mph<br>
</li>
<li><code>Acc060</code> - Time (in seconds) to go from 0 to 60 mph<br>
</li>
<li><code>QtrMile</code> - Time (in seconds) to go 1/4 mile<br>
</li>
<li><code>Braking</code> - Distance to stop from 60 mph (dry pavement)<br>
</li>
<li><code>FuelCap</code> - Fuel capacity (in gallons)<br>
</li>
<li><code>Length</code> - Length (in inches)<br>
</li>
<li><code>Width</code> - Width (in inches)<br>
</li>
<li><code>Height</code> - Height (in inches)<br>
</li>
<li><code>Wheelbase</code> - Wheelbase (in inches)<br>
</li>
<li><code>UTurn</code> - Diameter (in feet) needed for a U-turn<br>
</li>
<li><code>Weight</code> - Curb weight (in pounds)<br>
</li>
<li><code>Size</code> - Large, Midsized, or Small</li>
</ul>
<p>We’ll start by creating some graphs and tables to explore the data.</p>
<p>We’ll look at a summary of the categorical variables in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>Cars_Cat <span class="ot">&lt;-</span> <span class="fu">select_if</span>(Cars2020, is.factor)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_Cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Make         Model            Type    Drive          Size   
 Chevrolet: 8   3       :  1   Hatchback: 4   AWD:80   Large   :21  
 Toyoto   : 7   3 Series:  1   Minivan  : 4   FWD:25   Midsized:41  
 Audi     : 6   300     :  1   Sedan    :38   RWD: 5   Small   :48  
 Hyundai  : 6   4Runner :  1   Sporty   :11                         
 Nissan   : 6   5 series:  1   SUV      :50                         
 BMW      : 5   500L    :  1   Wagon    : 3                         
 (Other)  :72   (Other) :104                                        </code></pre>
</div>
</div>
<p>We examine the correlation matrix and plot of quantitative variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>Cars_Num <span class="ot">&lt;-</span> <span class="fu">select_if</span>(Cars2020, is.numeric)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">cor</span>(Cars_Num, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(C,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Price Acc060 CityMPG HwyMPG Seating Acc030 QtrMile Braking FuelCap
Price      1.00  -0.66   -0.48  -0.47    0.16  -0.66   -0.67   -0.02    0.57
Acc060    -0.66   1.00    0.52   0.45    0.02   0.95    0.98    0.27   -0.50
CityMPG   -0.48   0.52    1.00   0.88   -0.58   0.52    0.49   -0.22   -0.84
HwyMPG    -0.47   0.45    0.88   1.00   -0.52   0.48    0.43   -0.19   -0.78
Seating    0.16   0.02   -0.58  -0.52    1.00   0.01    0.07    0.63    0.64
Acc030    -0.66   0.95    0.52   0.48    0.01   1.00    0.95    0.26   -0.51
QtrMile   -0.67   0.98    0.49   0.43    0.07   0.95    1.00    0.34   -0.46
Braking   -0.02   0.27   -0.22  -0.19    0.63   0.26    0.34    1.00    0.35
FuelCap    0.57  -0.50   -0.84  -0.78    0.64  -0.51   -0.46    0.35    1.00
Length     0.45  -0.48   -0.69  -0.52    0.63  -0.43   -0.43    0.41    0.81
Width      0.50  -0.49   -0.78  -0.73    0.63  -0.47   -0.44    0.28    0.80
Height     0.12   0.09   -0.60  -0.65    0.81   0.06    0.16    0.63    0.63
Wheelbase  0.43  -0.43   -0.69  -0.55    0.62  -0.39   -0.39    0.44    0.80
UTurn      0.51  -0.47   -0.79  -0.69    0.61  -0.42   -0.41    0.35    0.81
Weight     0.58  -0.45   -0.86  -0.82    0.72  -0.46   -0.41    0.44    0.92
LogPrice   0.96  -0.72   -0.62  -0.58    0.23  -0.72   -0.71    0.01    0.67
          Length Width Height Wheelbase UTurn Weight LogPrice
Price       0.45  0.50   0.12      0.43  0.51   0.58     0.96
Acc060     -0.48 -0.49   0.09     -0.43 -0.47  -0.45    -0.72
CityMPG    -0.69 -0.78  -0.60     -0.69 -0.79  -0.86    -0.62
HwyMPG     -0.52 -0.73  -0.65     -0.55 -0.69  -0.82    -0.58
Seating     0.63  0.63   0.81      0.62  0.61   0.72     0.23
Acc030     -0.43 -0.47   0.06     -0.39 -0.42  -0.46    -0.72
QtrMile    -0.43 -0.44   0.16     -0.39 -0.41  -0.41    -0.71
Braking     0.41  0.28   0.63      0.44  0.35   0.44     0.01
FuelCap     0.81  0.80   0.63      0.80  0.81   0.92     0.67
Length      1.00  0.73   0.46      0.92  0.81   0.79     0.54
Width       0.73  1.00   0.64      0.75  0.76   0.86     0.64
Height      0.46  0.64   1.00      0.48  0.58   0.72     0.21
Wheelbase   0.92  0.75   0.48      1.00  0.82   0.82     0.53
UTurn       0.81  0.76   0.58      0.82  1.00   0.84     0.62
Weight      0.79  0.86   0.72      0.82  0.84   1.00     0.69
LogPrice    0.54  0.64   0.21      0.53  0.62   0.69     1.00</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">corrplot</span>(C)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>We see there is strong correlation between many of the variables. We’ll want to include variables that are highly correlated with price in the model. At the same time, we’ll see that including too many explanatory variables, especially when they are highly correlated, makes the model hard to interpret. We’ll need to carefully select explanatory variables that help us answer the questions we’re most interested in.</p>
<p>So far, we’ve explored the relationship between price and acceleration time. We found that modeling log(Price) as a function of acceleration time was more consistent with regression model assumptions than modeling price itself, so we’ll start there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>M_Cars1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.90992 -0.19686  0.00148  0.15566  0.63774 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)  5.00390    0.14547   34.40 &lt;0.0000000000000002 ***
Acc060      -0.19889    0.01821  -10.92 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.298 on 108 degrees of freedom
Multiple R-squared:  0.5248,    Adjusted R-squared:  0.5204 
F-statistic: 119.3 on 1 and 108 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>We see that just over 50% of the total variability in log(Price) is explained by acceleration time alone. Let’s investigate what other variables we should add to the model to better understand the factors contributing to the price of a car.</p>
<p>Along the way, we’ll discover some statistical considerations we should think about when building models.</p>
</section>
<section id="simpsons-paradox" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="simpsons-paradox"><span class="header-section-number">5.5.2</span> Simpson’s Paradox</h3>
<p>Let’s next investigate the effect of a car’s gas mileage on price. There are two gas mileage variables in the dataset, CityMPG and HwyMPG. We’ll use HwyMPG, which is the number of miles the car can go on one mile of gas when driving on the highway. We’ll also account for the weight of the car in lbs. The plot below shows the relationships between each of these variables with log(Price), as well as the relationship between Weight and Hwy MPG.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>HwyMPG, <span class="at">y=</span><span class="fu">log</span>(Price))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>HwyMPG, <span class="at">y=</span><span class="fu">log</span>(Price))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span>Weight, <span class="at">y=</span>HwyMPG)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() </span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that both highway MPG and weight are negatively associated with price, and that there is also a negative relationship between weight and highway MPG.</p>
<p>Let’s add highway gas mileage to our model, along with acceleration time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>M_Cars2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">+</span> HwyMPG)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 + HwyMPG, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.88944 -0.14122 -0.00675  0.15266  0.64910 

Coefficients:
             Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)  5.339932   0.151927  35.148 &lt; 0.0000000000000002 ***
Acc060      -0.160005   0.018699  -8.557   0.0000000000000918 ***
HwyMPG      -0.018843   0.004075  -4.624   0.0000105782710393 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2733 on 107 degrees of freedom
Multiple R-squared:  0.604, Adjusted R-squared:  0.5966 
F-statistic: 81.59 on 2 and 107 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>As the plot showed, highway MPG has a negative coefficient. Assuming acceleration time is held constant, price is expected to multiply by a factor of <span class="math inline">\(e^{-0.02} =0.98\)</span>, a 2 percent decrease.</p>
<p>It may be surprising to learn that cars that get better gas mileage tend to be less expensive than those with lower gas mileage. We see in the summary output that the p-value associated with <code>HwyMPG</code> is small, indicating a statistically discernible relationship.</p>
<p>We’ve learned, however, that when something seems unusual, we should think deeper. We noticed that highway gas mileage was negativly associated with weight, and that both are negatively associated with price. Since heaviest cars tend to also be the most expensive, it may be that cars that get better gas mileage are less expensive because they they are smaller and weigh less.</p>
<p>In the figure below we break the cars into three categories, based on their weight.</p>
<p>Light = less than 3,500 lbs.<br>
Medium = between 3,500 and 4,500 lbs.<br>
Heavy = heavier than 4,500 lbs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>Cars2020 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(Cars2020, <span class="at">Weight_Group =</span> <span class="fu">cut</span>(Weight, </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3500</span>, <span class="dv">4500</span>, <span class="dv">6500</span>), </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Light Weight"</span>, <span class="st">"Medium Weight"</span>, <span class="st">"Heavy Weight"</span>)))</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>( <span class="at">y=</span>Price, <span class="at">x=</span>HwyMPG )) <span class="sc">+</span><span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="at">facets =</span> <span class="sc">~</span>Weight_Group) <span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"Highway MPG"</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Once we compare cars of similar weights, we see that there is little to no relationship between highway MPG and price. The negative trend for low weight cars is due primarily to one outlier, while the other two weights show slightly positive to no trend. This is different than the strong negative relationship we saw in the previous graph.</p>
<p>Let’s add weight to the model and see what happens to to estimate associated with highway MPG.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>M_Cars3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">+</span> HwyMPG <span class="sc">+</span> Weight)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 + HwyMPG + Weight, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.65689 -0.16159 -0.01278  0.13494  0.91927 

Coefficients:
               Estimate  Std. Error t value           Pr(&gt;|t|)    
(Intercept)  3.40468799  0.37981919   8.964 0.0000000000000120 ***
Acc060      -0.14489669  0.01683344  -8.608 0.0000000000000751 ***
HwyMPG       0.00500984  0.00567833   0.882               0.38    
Weight       0.00025961  0.00004763   5.451 0.0000003294667341 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2427 on 106 degrees of freedom
Multiple R-squared:  0.6907,    Adjusted R-squared:  0.6819 
F-statistic: 78.89 on 3 and 106 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Notice that when weight is added to the model, the coefficient on HwyMPG changes signs and is now positive. This means that assuming we are comparing cars of the same acceleration time and weight, one with higher highway gas mileage is expected to cost more than one with lower gas mileage. The difference is small, with price expected to multiply by about <span class="math inline">\(e^{0.01} =1.01\)</span> (a -0.5022407) percent increase), and not statistically discernible (high p-value). So, there really doesn’t appear to be much of a relationship at all between price and gas mileage, after accounting for acceleration time and weight.</p>
<p>Still, this is a different conclusion than we would have drawn if we had not accounted for weight in the model. It had originally appeared that highway MPG had a strong negative association with price, but we see that once we compare cars of similar weights, there is little to no relationship between price and highway MPG. This is an example of a phenomenon know as <strong>Simpson’s Paradox.</strong> In instances of Simpson’s Paradox, the relationship between two variables changes directions, or disappears once a third variable is accounted for. The weight variable is called a <strong>confounding variable</strong>. If we don’t account for weight, we get a misleading picture of the relationship between highway gas mileage and price.</p>
<p>We saw that accounting for weight helps us better understand the relationship between price and gas mileage. We should also discuss the relationship between price and weight itself. Since weights of cars range from 2,000 to 6,000 lbs, it would be silly to talk about the effect of a single additional pound. Rather, let’s examine the effect of a 1,000 pound increase on price of a car. For each additional 1,000 lbs., price is expected to multiply by a factor of <span class="math inline">\(e^{0.00026 \times 1000} =1000.259645\)</span>, a 29.6426102 percent increase.</p>
<p>Our model with weight and highway gas mileage, in addition to acceleration time, now explains about 69.0673511 percent of the variability in log(Price), up from 52.4840462 for the model with only acceleration time.</p>
<p>We saw in the preceding graph, that the direction of the relationship between price and gas mileage was negative for light weight cars and positive for medium weight ones, suggesting a possible interaction between weight and gas mileage. So, we might consider adding an interaction term to the model. The <code>:</code> command adds just the interaction term.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>M_Cars4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">+</span> HwyMPG <span class="sc">+</span> Weight <span class="sc">+</span> HwyMPG<span class="sc">:</span>Weight)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 + HwyMPG + Weight + HwyMPG:Weight, 
    data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.63443 -0.14677 -0.01321  0.13097  0.94847 

Coefficients:
                  Estimate   Std. Error t value         Pr(&gt;|t|)    
(Intercept)    3.879767385  0.490968739   7.902 0.00000000000286 ***
Acc060        -0.135947988  0.017745763  -7.661 0.00000000000960 ***
HwyMPG        -0.014894324  0.014310665  -1.041            0.300    
Weight         0.000095708  0.000118187   0.810            0.420    
HwyMPG:Weight  0.000006049  0.000003997   1.514            0.133    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2412 on 105 degrees of freedom
Multiple R-squared:  0.6973,    Adjusted R-squared:  0.6857 
F-statistic: 60.46 on 4 and 105 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>The coefficient estimate on the interaction term is small and the p-value is large, telling us we don’t have much evidence of an interaction between weight and MPG. Also notice that <span class="math inline">\(R^2\)</span> barely changed, moving from 0.691 to 0.697 when the interaction term is included. Since interactions make the model harder to interpret, we shouldn’t include one unless we have good reason to. So, in this case, we’ll stick with the simpler model with no interaction term.</p>
</section>
<section id="multicollinearity" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="multicollinearity"><span class="header-section-number">5.5.3</span> Multicollinearity</h3>
<p>Let’s continue to add variables to our model that might help us learn about factors affecting the price of a car. Another variable in the dataset was the amount of time it takes a car to drive a quarter mile. We’ll add that variable to the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>M_Cars5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">+</span> HwyMPG <span class="sc">+</span> Weight <span class="sc">+</span> QtrMile)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 + HwyMPG + Weight + QtrMile, 
    data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73603 -0.15035 -0.00338  0.12601  0.83499 

Coefficients:
              Estimate Std. Error t value     Pr(&gt;|t|)    
(Intercept)  4.9556985  0.8375191   5.917 0.0000000415 ***
Acc060      -0.0001390  0.0718750  -0.002       0.9985    
HwyMPG       0.0067463  0.0056549   1.193       0.2356    
Weight       0.0002825  0.0000482   5.862 0.0000000534 ***
QtrMile     -0.1766120  0.0853267  -2.070       0.0409 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.239 on 105 degrees of freedom
Multiple R-squared:  0.7028,    Adjusted R-squared:  0.6915 
F-statistic: 62.07 on 4 and 105 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>The coefficient estimate for QtrMile time is negative , which is not surprising. We would expect cars that take longer to drive a quarter mile to be less expensive. But, look at what happened to the Acc060 variable. The estimate now is very slightly negative (a change from Model M_Cars4), but the most striking change is in the standard error column. The standard error associated with the Acc060 variable increased from 0.017 to 0.072, (more than 4 times larger). This has a big impact on the t-statistic, p-value, and confidence intervals associated with Acc060. Since standard errors are used to calculate confidence intervals, it will impact these as well.</p>
<p><strong>Confidence Interval for Acceleration Time - Model without Quarter Mile Time</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(M_Cars3, <span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm=</span><span class="st">"Acc060"</span>)) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 % 97.5 %
Acc060  0.84   0.89</code></pre>
</div>
</div>
<p>We are 95% confident that a 1-second increase in acceleration time is associated with an average price decrease between 11 and 16 percent, assuming weight and highway gas mileage are held constant.</p>
<p><strong>Confidence Interval for Acceleration Time - Model with Quarter Mile Time</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(M_Cars5, <span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm=</span><span class="st">"Acc060"</span>)) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 % 97.5 %
Acc060  0.87   1.15</code></pre>
</div>
</div>
<p>We are 95% confident that a 1-second increase in acceleration time is associated with an average price change between a 13 decrease and a 15 percent increase, assuming weight, highway gas mileage, and quarter mile time are held constant.</p>
<p>Notice how the second interval is so much wider than the first that it is practically useless. It tells us almost nothing about the relationship between price and acceleration time. This happens because quarter mile time is strongly correlated with Acc060. Recall their correlation was 0.98. When we add an explanatory variable that is highly correlated with a variable already in the model, the model will be unable to separate the effect of one variable from the effect of the other, causing it to yield high standard errors, reflecting lots of uncertainty about the effect of both variables. Further, recall that interpreting one variable in a multiple regression model requires assuming all others are held constant. But, if a can accelerate faster, it will most surely be able to drive a quarter mile more quickly, so it doesn’t make sense to talk about increasing acceleration time while holding quarter mile time constant.</p>
<p><strong>Key Point:</strong> Stong correlation between explanatory variables in a model is bad. This is called <strong>multicollinearity</strong>. When building a model, avoid including strongly correlated explanatory variables. Pick the one you think is most relevant and draw conclusions based on it. Generally, explanatory variables with correlation above 0.8 probably shouldn’t be included in the same model. If you are unsure whether multicollinearity will be a problem, you could look at how standard error on one variable changes when a second variable is added to the model. If standard error for the first variable increases then we should be cautious about adding the second variable. (Note: Correlation between the explanatory and response variables is not a problem. It’s generally a good thing because it means our model will be able to make more accurate predictions.)</p>
<p><strong>Impact of Multicollinearity on Prediction</strong></p>
<p>We’ve seen that multicollinearity can have a substantial affect on confidence intervals for regression coefficients <span class="math inline">\(b_j\)</span>. Let’s see how multicollinearity affects predicted values.</p>
<p>Suppose we want to predict the price of a car that can accelerate from 0 to 60 mph in 9.5 seconds, weighs 4000 lbs, gets 25 mpg on the highway, and completes a quarter mile in 17.5 seconds.</p>
<p><strong>Prediction interval based on Model without Quarter Mile Time:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars3, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fl">9.5</span>, </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Weight =</span> <span class="dv">4000</span>, <span class="at">HwyMPG =</span> <span class="dv">25</span>, </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">QtrMile=</span><span class="fl">17.3</span>), <span class="at">level=</span><span class="fl">0.95</span>, </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">interval=</span><span class="st">"prediction"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 24.33366 14.79947 40.01001</code></pre>
</div>
</div>
<p><strong>Prediction interval based on Model with Quarter Mile Time:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars5, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fl">9.5</span>, </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Weight =</span> <span class="dv">4000</span>, </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">HwyMPG =</span> <span class="dv">25</span>, </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">QtrMile=</span><span class="fl">17.3</span>), </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">level=</span><span class="fl">0.95</span>, <span class="at">interval=</span><span class="st">"prediction"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 24.47924 14.99922 39.95096</code></pre>
</div>
</div>
<p>We see that the predicted values and intervals are nearly identical. While multicollinearity has a severe impact on confidence intervals for model estimates, it does not affect predictions or prediction intervals.</p>
</section>
<section id="model-comparison-tests" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="model-comparison-tests"><span class="header-section-number">5.5.4</span> Model Comparison Tests</h3>
<p>Next, we’ll consider adding categorical explanatory variables Size, and Drive. The plot shows the relationship between each of these variables and price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(Price), <span class="at">y=</span>Size)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Price by Size"</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2020, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(Price), <span class="at">y=</span>Drive)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Price by Drive"</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>We’ve already included information about size, through the weight variable, so we won’t <code>Size</code> it too. Let’s add drive type to the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>M_Cars6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2020, <span class="fu">log</span>(Price) <span class="sc">~</span> Acc060 <span class="sc">+</span> HwyMPG <span class="sc">+</span> Weight <span class="sc">+</span> Drive)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Cars6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Price) ~ Acc060 + HwyMPG + Weight + Drive, data = Cars2020)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.52142 -0.12972 -0.00994  0.13284  0.85043 

Coefficients:
               Estimate  Std. Error t value         Pr(&gt;|t|)    
(Intercept)  3.43598628  0.41499637   8.280 0.00000000000045 ***
Acc060      -0.14665443  0.01848492  -7.934 0.00000000000257 ***
HwyMPG       0.00895120  0.00586769   1.526          0.13017    
Weight       0.00023446  0.00004935   4.751 0.00000651159314 ***
DriveFWD    -0.19735323  0.06537983  -3.019          0.00319 ** 
DriveRWD    -0.20279168  0.12475953  -1.625          0.10709    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2325 on 104 degrees of freedom
Multiple R-squared:  0.7215,    Adjusted R-squared:  0.7081 
F-statistic: 53.89 on 5 and 104 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>The baseline category for drive is AWD (all wheel drive). We see that FWD (front wheel) and RWD (rear wheel) both have negative estimates, indicating cars of these drive types tend to be less expensive than all wheel drive cars. Because the sample size for RWD cars is very small (only 5 cars), the difference between rear and all wheel drive cars is not statistically discernible, but the difference between FWD and AWD (which is roughly the same size), is statistically discernible.</p>
<p>We can use an ANOVA F-test to see if there is evidence of a relationship between price and drive type overall. We’ll compare the model that includes acceleration time, weight, and gas mileage, but not drive type (M_Cars3) to a model that includes these variables plus drive type (M_Cars6) .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M_Cars3, M_Cars6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Price) ~ Acc060 + HwyMPG + Weight
Model 2: log(Price) ~ Acc060 + HwyMPG + Weight + Drive
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    106 6.2444                                
2    104 5.6216  2   0.62282 5.7611 0.004238 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The large F-statistic and small p-value provides evidence of a relationship between price and drive type after accounting for the other variables, suggesting we should add drive type to the model. We found evidence of differences in price between front-wheel drive and rear-wheel drive, compared to all wheel drive cars. Adding drive type to the model results in a modest increase in <span class="math inline">\(R^2\)</span>, as the model now explains about 72.2 percent of the variability in Log(Price).</p>
<p>Model comparison tests can be helpful in deciding whether variables should be added to a model. We should keep in mind that when sample size is very large, even very small differences will return statistically discernible differences using the F-test, so we should also consider factors like <span class="math inline">\(R^2\)</span>, the size of our estimate(s) <span class="math inline">\(b_j\)</span>, background knowledge, and the variable’s relevance to our research question, when deciding whether or not to add it to a model.</p>
</section>
<section id="checking-model-assumptions" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="checking-model-assumptions"><span class="header-section-number">5.5.5</span> Checking Model Assumptions</h3>
<p>We could keep looking at other variables to add, but at this point, we have a model that gives us a good sense of the factors related to price of a car, capturing 72 of total variability in car price, and is still easy to interpret. Furthermore, other variables that are correlated with price (such as fuel capacity, length, width, wheelbase, and UTurn diameter) are highly correlated with variables already in the model. Adding them to the model will do little to explain variability in price, and could create problems associated with multicollinearilty. For our research purposes, our model is good enough.</p>
<p>We’ll use residuals to check the model assumptions.</p>
<p><strong>Residual by Predicted Plot, Histogram of Residuals, and Normal Quantile-Quantile Plot</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(M_Cars6, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>There is slight concern about constant variance, but otherwise, the model assumptions look good.</p>
<p><strong>Residual by Predictor Plots</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_xpanel</span>(M_Cars6, <span class="at">smoother=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch5_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>These plots don’t raise any concerns.</p>
</section>
<section id="interpretations" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="interpretations"><span class="header-section-number">5.5.6</span> Interpretations</h3>
<p>The model coefficients are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>M_Cars6<span class="sc">$</span>coefficients <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      Acc060      HwyMPG      Weight    DriveFWD    DriveRWD 
      3.436      -0.147       0.009       0.000      -0.197      -0.203 </code></pre>
</div>
</div>
<p>Since we used a log transformation, we should interpret <span class="math inline">\(e^{b_j}\)</span> rather than <span class="math inline">\(b_j\)</span> itself.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(M_Cars6<span class="sc">$</span>coefficients) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      Acc060      HwyMPG      Weight    DriveFWD    DriveRWD 
    31.0620      0.8636      1.0090      1.0002      0.8209      0.8164 </code></pre>
</div>
</div>
<p>The intercept theoretically tells us that a car that accelerates from 0 to 60 mph in no time, gets 0 mpg, weighs 0 lbs, and is AWD would be expected to cost 31.062, 0.8636, 1.009, 1.0002, 0.8209, 0.8164 thousand dollars. This statement is nonsensical and we shouldn’t try to interpret the intercept.</p>
<p>The price of a car is expected to decrease by 14 percent for each additional second it takes to accelerate from 0 to 60 mph, assumping highway MPG, weight and type of drive are held constant.</p>
<p>The price of a car is expected to increase by 0.9 percent for each additional highway MPG, assumping acceleration time, weight and type of drive are held constant.</p>
<p>The price of a car is expected to increase by 0.023 percent for each additional pound in weight, assumping acceleration time, highway MPG, and type of drive are held constant. This is equivalent to a 23 percent increase for each additional 1,000 pounds in weight.</p>
<p>FWD cars are expected to cost 18 less than AWD cars, assuming acceleration time, highway MPG, and weight are held constant.</p>
<p>RWD cars are expected to cost 18 less than AWD cars, assuming acceleration time, highway MPG, and weight are held constant.</p>
<p>Referring back to the model summary output, we saw that the effects associated with acceleration time, weight and the difference between FWD and AWD were statistically discernible, while the effect of highway MPG and the difference between RWD and AWD are not.</p>
</section>
<section id="predictions" class="level3" data-number="5.5.7">
<h3 data-number="5.5.7" class="anchored" data-anchor-id="predictions"><span class="header-section-number">5.5.7</span> Predictions</h3>
<p>We’ll use our model to estimate the average price with the following characteristics, and also to predict the price of a new car with the given characteristics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>newcar <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Acc060 =</span> <span class="dv">8</span>, <span class="at">Weight=</span><span class="dv">3000</span>, <span class="at">HwyMPG =</span> <span class="dv">30</span>, <span class="at">Drive =</span> <span class="st">"AWD"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is an interval for log(Price).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(M_Cars6, <span class="at">newdata=</span>newcar, <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 3.234658 3.100603 3.368712</code></pre>
</div>
</div>
<p>Exponentiating, we obtain</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars6, <span class="at">newdata=</span>newcar, <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level=</span><span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 25.39768 22.21135 29.0411</code></pre>
</div>
</div>
<p>We are 95% confident that the average price of all new 2020 cars that weigh 3000 lbs, take 8 seconds to accelerate from 0 to 60 mph, weigh 3,000 lbs, and have all wheel drive will cost between 22 and 29 thousand dollars.</p>
<p>Next, we calculate a prediction interval for an individual car with these characteristics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(M_Cars6, <span class="at">newdata=</span>newcar, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 25.39768 15.71348 41.05023</code></pre>
</div>
</div>
<p>We are 95% confident that the price of an individual car that weighs 3000 lbs, takes 8 seconds to accelerate from 0 to 60 mph, weighs 3,000 lbs, and has all wheel drive will cost between 16 and 41 thousand dollars.</p>
</section>
<section id="model-building-summary" class="level3" data-number="5.5.8">
<h3 data-number="5.5.8" class="anchored" data-anchor-id="model-building-summary"><span class="header-section-number">5.5.8</span> Model Building Summary</h3>
<p>Consider the following when building a model for the purpose of interpreting parameters and understanding and drawing conclusions about a population or process.</p>
<p><strong>Characteristics of a good model:</strong></p>
<ul>
<li>Model driven by research question</li>
<li>Include variables of interest<br>
</li>
<li>Include potential confounding variables<br>
</li>
<li>Avoid including highly correlated explanatory variables<br>
</li>
<li>Avoid messy transformations and interactions where possible<br>
</li>
<li>Use residual plots to assess appropriateness of model assumptions<br>
</li>
<li>Aim for high <span class="math inline">\(R^2\)</span> but not highest<br>
</li>
<li>Aim for model complex enough to capture nature of data, but simple enough to give clear interpretations<br>
</li>
</ul>
<p>Keep in mind, there is no single correct model, but there are common characteristics of a good model. While two statisticians might use different models for a given set of data, they will hopefully lead to reasonably similar conclusions if constructed carefully.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch4.html" class="pagination-link" aria-label="Inference from Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference from Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>