<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Logistic Regression – STAT 255 Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch7.html" rel="next">
<link href="./Ch5.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch6.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Logistic Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">STAT 255 Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Statistical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation-Based Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference from Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Building and Assessing Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Predictive Modeling</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">6.1</span> Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#modeling-binary-response" id="toc-modeling-binary-response" class="nav-link" data-scroll-target="#modeling-binary-response"><span class="header-section-number">6.1.1</span> Modeling Binary Response</a></li>
  <li><a href="#credit-card-dataset" id="toc-credit-card-dataset" class="nav-link" data-scroll-target="#credit-card-dataset"><span class="header-section-number">6.1.2</span> Credit Card Dataset</a></li>
  <li><a href="#logistic-regression-model" id="toc-logistic-regression-model" class="nav-link" data-scroll-target="#logistic-regression-model"><span class="header-section-number">6.1.3</span> Logistic Regression Model</a></li>
  <li><a href="#odds-and-odds-ratio" id="toc-odds-and-odds-ratio" class="nav-link" data-scroll-target="#odds-and-odds-ratio"><span class="header-section-number">6.1.4</span> Odds and Odds Ratio</a></li>
  <li><a href="#interpretation-and-of-beta_1" id="toc-interpretation-and-of-beta_1" class="nav-link" data-scroll-target="#interpretation-and-of-beta_1"><span class="header-section-number">6.1.5</span> Interpretation and of <span class="math inline">\(\beta_1\)</span></a></li>
  </ul></li>
  <li><a href="#multiple-logistic-regression" id="toc-multiple-logistic-regression" class="nav-link" data-scroll-target="#multiple-logistic-regression"><span class="header-section-number">6.2</span> Multiple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-models-with-multiple-explanatory-variables" id="toc-logistic-regression-models-with-multiple-explanatory-variables" class="nav-link" data-scroll-target="#logistic-regression-models-with-multiple-explanatory-variables"><span class="header-section-number">6.2.1</span> Logistic Regression Models with Multiple Explanatory Variables</a></li>
  <li><a href="#multiple-logistic-regression-model-with-interaction" id="toc-multiple-logistic-regression-model-with-interaction" class="nav-link" data-scroll-target="#multiple-logistic-regression-model-with-interaction"><span class="header-section-number">6.2.2</span> Multiple Logistic Regression Model with Interaction</a></li>
  <li><a href="#logistic-regression-key-points" id="toc-logistic-regression-key-points" class="nav-link" data-scroll-target="#logistic-regression-key-points"><span class="header-section-number">6.2.3</span> Logistic Regression Key Points</a></li>
  </ul></li>
  <li><a href="#practice-questions" id="toc-practice-questions" class="nav-link" data-scroll-target="#practice-questions"><span class="header-section-number">6.3</span> Practice Questions</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">1)</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">2)</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">3)</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">4)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Logistic Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-outcomes" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h3>
<p><strong>Conceptual Learning Outcomes</strong><br>
24. Calculate probabilities and odds using logistic regression.<br>
25. Interpret logistic regression coefficients in context.<br>
</p>
<p><strong>Computational Learning Outcomes</strong><br>
J. Perform logistic regression in R.</p>
</section>
<section id="logistic-regression" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">6.1</span> Logistic Regression</h2>
<section id="modeling-binary-response" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="modeling-binary-response"><span class="header-section-number">6.1.1</span> Modeling Binary Response</h3>
<p>So far, we have modeled only quantitative response variables. The normal error regression model makes the assumption that the response variable is normally distributed, given the value(s) of the explanatory variables.</p>
<p>Now, we’ll look at how to model a categorical response variable. We’ll consider only situations where the response is binary (i.e.&nbsp;has 2 categories). Problems with categorical response variables are sometimes called <strong>classification</strong> problems, while problems with numeric response variables are sometimes called <strong>regression</strong> problems.</p>
</section>
<section id="credit-card-dataset" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="credit-card-dataset"><span class="header-section-number">6.1.2</span> Credit Card Dataset</h3>
<p>We’ll work with a dataset pertaining to 10,000 credit cards. The goal is to predict whether or not the user will default on the payment, using information on the credit card balance, user’s annual income, and whether or not the user is a student. Data come from <a href="http://www-bcf.usc.edu/~gareth/ISL/data.html">Introduction to Statistical Learning</a> by James, Witten, Hastie, Tibshirani.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Default)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> default    student       balance           income     
 No :9667   No :7056   Min.   :   0.0   Min.   :  772  
 Yes: 333   Yes:2944   1st Qu.: 481.7   1st Qu.:21340  
                       Median : 823.6   Median :34553  
                       Mean   : 835.4   Mean   :33517  
                       3rd Qu.:1166.3   3rd Qu.:43808  
                       Max.   :2654.3   Max.   :73554  </code></pre>
</div>
</div>
<p><strong>Default and Balance</strong></p>
<p>The plot displays each person’s credit card balance on the x-axis, and whether or not they defaulted (a 0 or 1) on the y-axis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Default, <span class="fu">aes</span>(<span class="at">y=</span>default, <span class="at">x=</span>balance)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">height=</span><span class="fl">0.05</span>) <span class="sc">+</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>We see that defaults are rare when the balance is less than $1,000, and more common for balances above $2,000.</p>
<p>We’ll first try fitting a linear regression model to the data to try to estimate the probability of a person defaulting on a loan, using the size of their balance as the explanatory variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert default from yes/no to 0/1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Default <span class="ot">&lt;-</span> Default <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">default =</span> <span class="fu">as.numeric</span>(default<span class="sc">==</span><span class="st">"Yes"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Default, <span class="fu">aes</span>(<span class="at">y=</span>default, <span class="at">x=</span> balance)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">height=</span><span class="fl">0.05</span>)  <span class="sc">+</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>)  <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>There are a lot of problems with this model!</p>
<p>It allows the estimated probability of of default to be negative. It also assumes a linear trend that doesn’t seem to fit the data very well.</p>
<p>A sigmoidal curve, like the one below, seems like a better model for default probabilities. This curve stays between 0 and 1, and its curved nature seems like a better fit for the data.</p>
</section>
<section id="logistic-regression-model" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="logistic-regression-model"><span class="header-section-number">6.1.3</span> Logistic Regression Model</h3>
<p>A logistic regression model uses a sigmoidal curve like the one we saw to model default probabilities, using balance as an explanatory variable.</p>
<p>The model makes use of the function</p>
<p><span class="math display">\[ f(x) = \frac{e^x}{1+x^x}, \]</span></p>
<p>whose graph is shown below. This function is called an <strong>inverse logit</strong> function.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Starting with our linear model <span class="math inline">\(E(Y_i) = \beta_0+\beta_1x_{i1}\)</span>, we need to transform <span class="math inline">\(\beta_0+\beta_1x_{i1}\)</span> into the interval (0,1).</p>
<ul>
<li><p>Let <span class="math inline">\(\pi_i = \frac{e^{\beta_0+\beta_1x_{i1} }}{1+e^{\beta_0+\beta_1x_{i1}}}\)</span>.</p></li>
<li><p>Then <span class="math inline">\(0 \leq \pi_i \leq 1\)</span>, and <span class="math inline">\(\pi_i\)</span> represents an estimate of <span class="math inline">\(P(Y_i=1)\)</span>.</p></li>
<li><p>This function maps the values of <span class="math inline">\(\beta_0+\beta_1x_{i1}\)</span> into the interval (0,1).</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>logistic regression model</strong> assumes that:<br>
</p>
<ul>
<li><span class="math inline">\(Y_i \in \{0,1\}\)</span><br>
</li>
<li><span class="math inline">\(E(Y_i) = P(Y_i=1) = \pi_i=\frac{e^{\beta_0+\beta_1x_{i1} + \ldots \beta_px_{ip}}}{1+e^{\beta_0+\beta_1x_{i1} + \ldots \beta_px_{ip}}}\)</span> i.e.&nbsp;<span class="math inline">\(\beta_0+\beta_1x_{i1} + \ldots \beta_px_{ip}= \text{log}\left(\frac{\pi_i}{1-\pi_i}\right).\)</span> (This is called the logit function and can be written <span class="math inline">\(\text{logit}(\pi_i)\)</span>.</li>
</ul>
<p>Instead of assuming that the expected response is a linear function of the explanatory variables, we are assuming that it is a function of a linear function of the explanatory variables.</p>
<p>We fit the logistic curve to the credit card data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Default, <span class="fu">aes</span>(<span class="at">y=</span>default, <span class="at">x=</span> balance)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">height=</span><span class="fl">0.05</span>) <span class="sc">+</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span>binomial)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>To fit the logistic regression model in R, we use the function <code>glm</code>, instead of <code>lm</code>. The function is specified the same way as before, and we add <code>family = binomial(link = "logit")</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>CCDefault_M <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>Default, default <span class="sc">~</span> balance, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CCDefault_M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = default ~ balance, family = binomial(link = "logit"), 
    data = Default)

Coefficients:
               Estimate  Std. Error z value            Pr(&gt;|z|)    
(Intercept) -10.6513306   0.3611574  -29.49 &lt;0.0000000000000002 ***
balance       0.0054989   0.0002204   24.95 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2920.6  on 9999  degrees of freedom
Residual deviance: 1596.5  on 9998  degrees of freedom
AIC: 1600.5

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>The regression equation is:</p>
<p><span class="math display">\[ P(\text{Default}) = \hat{\pi}_i = \frac{e^{-10.65+0.0055\times\text{balance}}}{1+e^{-10.65+0.0055\times\text{balance}}} \]</span></p>
<p><strong>Predictions</strong></p>
<ul>
<li><p>For a $1,000 balance, the estimated default probability is <span class="math inline">\(\frac{e^{-10.65+0.0055(1000) }}{1+e^{-10.65+0.0055(1000)}} \approx 0.006\)</span></p></li>
<li><p>For a $1,500 balance, the estimated default probability is <span class="math inline">\(\frac{e^{-10.65+0.0055(1500) }}{1+e^{-10.65+0.0055(1500)}} \approx 0.08\)</span></p></li>
<li><p>For a $2,000 balance, the estimated default probability is <span class="math inline">\(\frac{e^{-10.65+0.0055(2000) }}{1+e^{-10.65+0.0055(2000)}} \approx 0.59\)</span></p></li>
</ul>
<p>We confirm these, using the <code>predict</code> command in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(CCDefault_M, <span class="at">newdata=</span><span class="fu">data.frame</span>((<span class="at">balance=</span><span class="dv">1000</span>)), <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1 
0.005752145 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(CCDefault_M, <span class="at">newdata=</span><span class="fu">data.frame</span>((<span class="at">balance=</span><span class="dv">1500</span>)), <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
0.08294762 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(CCDefault_M, <span class="at">newdata=</span><span class="fu">data.frame</span>((<span class="at">balance=</span><span class="dv">2000</span>)), <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.5857694 </code></pre>
</div>
</div>
<section id="where-do-the-bs-come-from" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="where-do-the-bs-come-from">Where do the b’s come from?</h4>
<p>Recall that for a quantitative response variable, the values of <span class="math inline">\(b_1, b_2, \ldots, b_p\)</span> are chosen in a way that minimizes <span class="math inline">\(\displaystyle\sum_{i=1}^n \left(y_i-(\beta_0+\beta_1x_{i1}+\ldots+\beta_px_{ip})^2\right)\)</span>. Least squares does not work well in this generalized setting. Instead, the b’s are calculated using a more advanced technique, known as <strong>maximum likelihood estimation</strong>. We won’t say anything more about that topic here, but it is a prominent technique, widely used in statistic modeling. It is explored in more detail in advanced statistics courses, such as STAT 445:Mathematical Statistics.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="odds-and-odds-ratio" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="odds-and-odds-ratio"><span class="header-section-number">6.1.4</span> Odds and Odds Ratio</h3>
<p>For an event with probability <span class="math inline">\(p\)</span>, the <strong>odds</strong> of the event occurring are <span class="math inline">\(\frac{p}{1-p}\)</span>.</p>
<p>Examples: 1. The odds of a fair coin landing heads are <span class="math inline">\(\frac{0.5}{1-0.5}=1\)</span>, sometimes written 1:1.</p>
<ol start="2" type="1">
<li>The odds of a fair 6-sided die landing on a 1 are <span class="math inline">\(\frac{1/6}{1-1/6}=\frac{1}{5}\)</span>, sometimes written 1:5.</li>
</ol>
<p>In the credit card example, the odds of default are:</p>
<ul>
<li><p>For a $1,000 balance - odds of default are <span class="math inline">\(\frac{0.00575}{1-0.00575} \approx 1:173.\)</span></p></li>
<li><p>For a $1,500 balance - odds of default are <span class="math inline">\(\frac{0.0829}{1-0.0829 } \approx 1:11.\)</span></p></li>
<li><p>For a $2,000 balance - odds of default are <span class="math inline">\(\frac{0.586}{1-0.586} \approx 1.414:1.\)</span></p></li>
</ul>
<p>The quantity <span class="math inline">\(\frac{\frac{\pi_i}{1-\pi_i}}{\frac{\pi_j}{1-\pi_j}}\)</span> is called the <strong>odds ratio</strong> and represents the odds ratio of a default for user <span class="math inline">\(i\)</span>, compared to user <span class="math inline">\(j\)</span>.</p>
<p>Example:</p>
<p>The default odds ratio for a $1,000 payment, compared to a $2,000 payment is</p>
<p>The odds ratio is <span class="math inline">\(\frac{\frac{1}{173}}{\frac{1.414}{1}}\approx 1:244.\)</span></p>
<p>The odds of a default are about 244 times larger for a $2,000 payment than a $1,000 payment.</p>
</section>
<section id="interpretation-and-of-beta_1" class="level3" data-number="6.1.5">
<h3 data-number="6.1.5" class="anchored" data-anchor-id="interpretation-and-of-beta_1"><span class="header-section-number">6.1.5</span> Interpretation and of <span class="math inline">\(\beta_1\)</span></h3>
<p>Consider the odds ratio for a case <span class="math inline">\(j\)</span> with explanatory variable <span class="math inline">\(x + 1\)</span>, compared to case <span class="math inline">\(i\)</span> with explanatory variable <span class="math inline">\(x\)</span>.</p>
<p>That is <span class="math inline">\(\text{log}\left(\frac{\pi_i}{1-\pi_i}\right) = \beta_0+\beta_1x\)</span>, and <span class="math inline">\(\text{log}\left(\frac{\pi_j}{1-\pi_j}\right) = \beta_0+\beta_1(x+1)\)</span>.</p>
<p><span class="math inline">\(\text{log}\left(\frac{\frac{\pi_j}{1-\pi_j}}{\frac{\pi_i}{1-\pi_i}}\right)=\text{log}\left(\frac{\pi_j}{1-\pi_j}\right)-\text{log}\left(\frac{\pi_i}{1-\pi_i}\right)=\beta_0+\beta_1(x+1)-(\beta_0+\beta_1(x))=\beta_1.\)</span></p>
<p>For every 1-unit increase in <span class="math inline">\(x\)</span> we expect the log odds of “success” to multiply by a factor of <span class="math inline">\(\beta_1\)</span>.</p>
<p>For every 1-unit increase in <span class="math inline">\(x\)</span> we expect the odds of “success” to multiply by a factor of <span class="math inline">\(e^{\beta_1}\)</span>.</p>
<p><strong>Interpretation in Credit Card Example</strong></p>
<p><span class="math inline">\(b_1=0.0055\)</span></p>
<p>For each 1-dollar increase in balance on the credit card., the odds of default are estimated to multiply by <span class="math inline">\(e^{0.0055}\approx1.0055\)</span>.</p>
<p>That is, for each additional dollar on the card balance, the odds of default are estimated to increase by 0.55%</p>
<p>For each increase of <span class="math inline">\(d\)</span> dollars in credit card balance, odds of default are estimated to multiply by a factor of <span class="math inline">\(e^{0.0055d}\)</span>.</p>
<p>For every $1,000 increase in balance, the odds of default are expected to multiply by a factor of <span class="math inline">\(e^{0.0055\times 1000}\approx 244\)</span>.</p>
<p>Thus, the odds of default for a balance of $2,000 are estimated to be <span class="math inline">\(e^{0.0055\times 1000}\approx 244\)</span> times as great as the odds of default for a $1,000 balance. This matches our result when we actually calculated out the probabilities and odds.</p>
<p><strong>Hypothesis test for</strong> <span class="math inline">\(\beta_1=0\)</span></p>
<p>The p-value on the “balance” line of the regression output is associated with the null hypothesis <span class="math inline">\(\beta_1=0\)</span>, that is that there is no relationship between balance and the odds of defaulting on the payment.</p>
<p>The fact that the p-value is so small tells us that there is strong evidence of a relationship between balance and odds of default.</p>
<p><strong>Confidence Intervals for</strong> <span class="math inline">\(\beta_1\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(CCDefault_M, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %       97.5 %
(Intercept) -11.383288936 -9.966565064
balance       0.005078926  0.005943365</code></pre>
</div>
</div>
<p>We are 95% confident that for each 1 dollar increase in credit card balance, the odds of default are expected to multiply by a factor between <span class="math inline">\(e^{0.00508}\approx 1.0051\)</span> and <span class="math inline">\(e^{0.00594}\approx 1.0060\)</span>.</p>
<p>This is a profile-likelihood interval, which you can read more about <a href="https://rpubs.com/FJRubio/PLCIN">here</a>.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="multiple-logistic-regression" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="multiple-logistic-regression"><span class="header-section-number">6.2</span> Multiple Logistic Regression</h2>
<section id="logistic-regression-models-with-multiple-explanatory-variables" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="logistic-regression-models-with-multiple-explanatory-variables"><span class="header-section-number">6.2.1</span> Logistic Regression Models with Multiple Explanatory Variables</h3>
<p>We can also perform logistic regression in situations where there are multiple explanatory variables. We’ll estimate probability of default, using both balance and whether or not the person is a student (a categorical variable) as explanatory variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>CCDefault_M2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>Default, default <span class="sc">~</span> balance <span class="sc">+</span> student, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CCDefault_M2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = default ~ balance + student, family = binomial(link = "logit"), 
    data = Default)

Coefficients:
               Estimate  Std. Error z value             Pr(&gt;|z|)    
(Intercept) -10.7494959   0.3691914 -29.116 &lt; 0.0000000000000002 ***
balance       0.0057381   0.0002318  24.750 &lt; 0.0000000000000002 ***
studentYes   -0.7148776   0.1475190  -4.846           0.00000126 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2920.6  on 9999  degrees of freedom
Residual deviance: 1571.7  on 9997  degrees of freedom
AIC: 1577.7

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>The following graph gives an illustration of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Default, <span class="fu">aes</span>(<span class="at">y=</span>default, <span class="at">x=</span> balance, <span class="at">color=</span>student)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">height=</span><span class="fl">0.05</span>) <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span>binomial)) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The regression equation is:</p>
<p><span class="math display">\[
P(\text{Default}) = \hat{\pi}_i = \frac{e^{-10.75+0.005738\times\text{balance}-0.71\times\text{student}_i}}{1+e^{-10.75+0.0057\times\text{balance}-0.71\times\text{student}_i}}
\]</span></p>
<ul>
<li><p>For each 1 dollar increase in balance, the odds of default are estimated to multiply by a factor <span class="math inline">\(e^{0.0057}\approx 1.00575\)</span>, assuming whether or not the person is a student is held constant. Thus, the estimated odds of default increase by about 0.5%, for each 1-dollar increase in balance..</p></li>
<li><p>For every $100 increase in balance, the odds of default are estimated to multiply by <span class="math inline">\(e^{0.0057\times100}\approx 1.775\)</span>, assuming whether or not the person is a student is held constant. Thus, the estimated odds of default increase by about 77.5%.</p></li>
<li><p>The odds of default for students are estimated to be <span class="math inline">\(e^{-0.71} \approx 0.49\)</span> as high for students as non-students, assuming balance amount is held constant.</p></li>
</ul>
<p><strong>Hypothesis Tests in Multiple Logistic Regression Model</strong></p>
<ul>
<li><p>Since the p-value associated with <code>balance</code> is very small, there is strong evidence of a relationship between balance and odds of default, after accounting for whether or not the person is a student.</p></li>
<li><p>Since the p-value associated with <code>StudentYes</code> is very small, there is strong evidence that students are less likely to default than nonstudents, provided the balance on the card is the same.</p></li>
</ul>
</section>
<section id="multiple-logistic-regression-model-with-interaction" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="multiple-logistic-regression-model-with-interaction"><span class="header-section-number">6.2.2</span> Multiple Logistic Regression Model with Interaction</h3>
<p>The previous model assumes the effect of balance on default probability is the same for students as for nonstudents. If we suspect that the effect of having a larger balance might be different for students than for nonstudents, then we could use a model with interaction between the balance and student variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>CCDefault_M_Int <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>Default, default <span class="sc">~</span> balance <span class="sc">*</span> student, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CCDefault_M_Int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = default ~ balance * student, family = binomial(link = "logit"), 
    data = Default)

Coefficients:
                      Estimate  Std. Error z value            Pr(&gt;|z|)    
(Intercept)        -10.8746818   0.4639679 -23.438 &lt;0.0000000000000002 ***
balance              0.0058188   0.0002937  19.812 &lt;0.0000000000000002 ***
studentYes          -0.3512310   0.8037333  -0.437               0.662    
balance:studentYes  -0.0002196   0.0004781  -0.459               0.646    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2920.6  on 9999  degrees of freedom
Residual deviance: 1571.5  on 9996  degrees of freedom
AIC: 1579.5

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p><strong>Interpretations for Logistic Model with Interaction</strong></p>
<ul>
<li>The regression equation is:</li>
</ul>
<p><span class="math display">\[
P(\text{Default}) = \hat{\pi}\_i = \frac{e^{-10.87+0.0058\times\text{balance}_i-0.35\times\text{student}_i-0.0002\times\text{balance}_i\times{\text{student}_i}}}{1+e^{-10.87+0.0058\times\text{balance}_i-0.35\times\text{student}_i-0.0002\times\text{balance}_i\times{\text{student}_i}}}
\]</span></p>
<p><strong>Equation for Students</strong></p>
<p><span class="math display">\[
P(\text{Default}) = \hat{\pi}\_i = \frac{e^{-10.52+0.0056\times\text{balance}}}{1+e^{-10.52+0.0056\times\text{balance}}}
\]</span></p>
<p>Assuming a person is a student, for every $100 increase in balance, the odds of default are expected to multiply by a factor of <span class="math inline">\(e^{0.0056\times 100}=1.75\)</span>, a 75% increase.</p>
<p><strong>Equation for Non-Students</strong></p>
<p><span class="math display">\[
P(\text{Default}) = \hat{\pi}\_i = \frac{e^{-10.87+0.0058\times\text{balance}}}{1+e^{-10.87+0.0058\times\text{balance}}}
\]</span></p>
<p>Assuming a person is a student, for every $100 increase in balance, the odds of default are expected to multiply by a factor of <span class="math inline">\(e^{0.0058\times 100}=1.786\)</span>, a 78.6% increase.</p>
<ul>
<li>Since estimate of the interaction effect is so small and the p-value on this estimate is large, it is plausible that there is no interaction at all. Thus, the simpler non-interaction model is preferable.</li>
</ul>
</section>
<section id="logistic-regression-key-points" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="logistic-regression-key-points"><span class="header-section-number">6.2.3</span> Logistic Regression Key Points</h3>
<ul>
<li><p><span class="math inline">\(Y\)</span> is a binary response variable.</p></li>
<li><p><span class="math inline">\(\pi_i\)</span> is a function of explanatory variables <span class="math inline">\(x_{i1}, \ldots x_{ip}\)</span>.</p></li>
<li><p><span class="math inline">\(E(Y_i) = \pi_i = \frac{e^{\beta_0+\beta_1x_i + \ldots\beta_px_{ip}}}{1+e^{\beta_0+\beta_1x_i + \ldots\beta_px_{ip}}}\)</span></p></li>
<li><p><span class="math inline">\(\beta_0+\beta_1x_i + \ldots\beta_px_{ip} = \text{log}\left(\frac{\pi_i}{1-\pi_i}\right)\)</span></p></li>
<li><p>For quantitative <span class="math inline">\(x_j\)</span>, when all other explanatory variables are held constant, the odds of “success” multiply be a factor of <span class="math inline">\(e^{\beta_j}\)</span> for each 1 unit increase in <span class="math inline">\(x_j\)</span></p></li>
<li><p>For categorical <span class="math inline">\(x_j\)</span>, when all other explanatory variables are held constant, the odds of “success” are <span class="math inline">\(e^{\beta_j}\)</span> times higher for category <span class="math inline">\(j\)</span> than for the “baseline category.”</p></li>
<li><p>For models with interaction, we can only interpret <span class="math inline">\(\beta_j\)</span> when the values of all other explanatory variables are given (since the effect of <span class="math inline">\(x_j\)</span> depends on the other variables.)</p></li>
</ul>
</section>
</section>
<section id="practice-questions" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="practice-questions"><span class="header-section-number">6.3</span> Practice Questions</h2>
<section id="section" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="section">1)</h3>
<p>In which of the following situations would it be appropriate to use a logistic regression model? Choose all that apply.</p>
<p>A. We want to predict whether or not it will rain on a given day, using information on temperature, wind speed, and amount of cloud cover.</p>
<p>B. We want to predict the number of hours a person will sleep in a given night, based on whether or not they take medication designed to improve sleep quality.</p>
<p>C. We want to predict whether the incumbent party will win an election, using information on unemployment and inflation rates, and stock market growth.</p>
<p>D. We want to predict whether a person will use the term “Pop” or “Soda” based on which state they grew up in.</p>
<p>E. We want to predict whether or not a person will get into a college, using information including their high school GPA, standardized test scores, and whether or not they participated in certain activities.</p>
<p>F. We want to predict the number of people crossing a street in a given hour, using information about the time of the day, the day of the week, and the temperature.</p>
<p>G. We want to predict whether or not a sports team will win a game, using information on the number of games they’ve won and lost previously, as well as the number of games their opponent has won and lost previously, as well as the strength of opponents that they and their opponent have played against in prior games.</p>
</section>
<section id="section-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="section-1">2)</h3>
<p><strong>We’ll work with a dataset on admissions to graduate school. We have data on a student’s graduate records exam (GRE) test score out of 800, and whether or not they attended a top-tier undergraduate college. Data are from (https://stats.idre.ucla.edu/stat/data/binary.csv). The response variable is whether or not the student was admitted to the graduate program (1=Yes, 0=No).</strong></p>
<p><strong>The dataset contains the following variables.</strong></p>
<p><code>gre</code> - score on the GRE exam<br>
<code>TopTier</code> - whether or not the student attended a top tier undergraduate institution<br>
<code>admit</code> - whether or not the student was admitted to the program (1=yes, 0=no)</p>
<p>A graph showing whether or not a person was admitted to graduate school along with their gre score and whether or not they attended a top tier undergraduate college is shown below. The curves estimating admission probability using logistic regression are also shown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Grad, <span class="fu">aes</span>(<span class="at">y=</span>admit, <span class="at">x=</span> gre, <span class="at">color=</span>TopTier)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">height=</span><span class="fl">0.05</span>) <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span>binomial)) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Ch6_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We fit a logistic regression model with <code>admit</code> as the response variable and <code>gre</code> and <code>TopTier</code> as explanatory variables.</p>
<p>R output for the model is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>M_Grad_admit_gre_top <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>Grad, admit <span class="sc">~</span> gre <span class="sc">+</span> TopTier, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Grad_admit_gre_top)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = admit ~ gre + TopTier, family = binomial(link = "logit"), 
    data = Grad)

Coefficients:
             Estimate Std. Error z value   Pr(&gt;|z|)    
(Intercept) -2.960822   0.617269  -4.797 0.00000161 ***
gre          0.003377   0.001004   3.363   0.000770 ***
TopTierTRUE  1.065127   0.289486   3.679   0.000234 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 499.98  on 399  degrees of freedom
Residual deviance: 472.56  on 397  degrees of freedom
AIC: 478.56

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Exponentiated regression coefficients are shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(M_Grad_admit_gre_top<span class="sc">$</span>coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         gre TopTierTRUE 
 0.05177633  1.00338305  2.90120814 </code></pre>
</div>
</div>
<section id="a" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="a">a)</h4>
<p>Give interpretations of each of the three numbers in the <code>Estimate</code> column of the coefficient table, in context. Give your answer in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
</section>
<section id="b" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="b">b)</h4>
<p>Write a sentence interpreting the confidence intervals on the “gre” and “HighlyRankedTRUE” lines in context. Give answers in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(M_Grad_admit_gre_top, <span class="at">level =</span> <span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) 0.01494934 0.1688771
gre         1.00143970 1.0053977
TopTierTRUE 1.64705190 5.1438511</code></pre>
</div>
</div>
</section>
<section id="c" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="c">c)</h4>
<p>Do the data provide evidence that higher GRE scores are associated with increased chance of being admitted to graduate school, for students attending similar institutions? Cite a p-value to support your answer.</p>
</section>
<section id="d" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="d">d)</h4>
<p>Do the data provide evidence that attending a highly ranked institution improves the chances for graduate school admission for students of the same GRE score?</p>
</section>
</section>
<section id="section-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="section-2">3)</h3>
<p>Continue with the R output from Question 2.</p>
<section id="a-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="a-1">a)</h4>
<p>Estimate the admission probability of a student who attended a top-tier institution and had a GRE score of 575. Give your answer as a probability in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
</section>
<section id="b-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="b-1">b)</h4>
<p>Estimate the admission probability of a student who did not attend a top-tier institution and had a GRE score of 650. Give your answer as a probability in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
</section>
<section id="c-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="c-1">c)</h4>
<p>If two students attend the same institution, and one scores 50 points higher on the GRE, how many times greater are the odds of that student to be admitted to the graduate program, compared to the student with the lower GRE score? Give your answer in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
</section>
<section id="d-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="d-1">d)</h4>
<p>If two students achieve the same GRE score, and one attended a top-tier institution, while the other did not, how many times greater are the odds of the student who attended the highly ranked institution being accepted to grad school, compared with the one who did not? Give your answer in rounded numeric form. (i.e.&nbsp;don’t put <span class="math inline">\(e^\#\)</span>.)</p>
</section>
<section id="e" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="e">e)</h4>
<p>Suppose that, according to the above model, Student A is estimated to have a 25% chance of getting into the the graduate program. Student B goes to the same school and scores 55 points higher on the GRE. Approximately, what is the estimated probability of student B getting into the graduate program?</p>
<p>Hint: The following calculation may be helpful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.003377</span><span class="sc">*</span><span class="dv">55</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.204103</code></pre>
</div>
</div>
</section>
</section>
<section id="section-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="section-3">4)</h3>
<p>Now, consider the logistic regression model resulting from the following R command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>M_Grad_admit_gre_top_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data=</span>Grad, admit <span class="sc">~</span> gre <span class="sc">*</span> TopTier, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Grad_admit_gre_top_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = admit ~ gre * TopTier, family = binomial(link = "logit"), 
    data = Grad)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -2.8825292  0.6839726  -4.214 0.000025 ***
gre              0.0032473  0.0011183   2.904  0.00369 ** 
TopTierTRUE      0.6630025  1.5695442   0.422  0.67272    
gre:TopTierTRUE  0.0006627  0.0025429   0.261  0.79439    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 499.98  on 399  degrees of freedom
Residual deviance: 472.49  on 396  degrees of freedom
AIC: 480.49

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="a-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="a-2">a)</h4>
<p>Explain, in context, how this model is different than the one in Questions 2 and 3. (Don’t just say that it contains an interaction, but rather, explain what that means in context.)</p>
</section>
<section id="b-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="b-2">b)</h4>
<p>Do the data provide evidence that gre score affects the probability of successful grad school admission differently for students at top tier schools than at other schools? Justify your answer.</p>
</section>
<section id="c-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="c-2">c)</h4>
<p>Which model should we use (this one or the one in Question 2) to make inferences? Explain your answer.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch5.html" class="pagination-link" aria-label="Building and Assessing Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Building and Assessing Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch7.html" class="pagination-link" aria-label="Predictive Modeling">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Predictive Modeling</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>